export const SECCIONALES: { code: string; name: string }[] = [
  { code: "01", name: "Barranquilla" },
  { code: "02", name: "Cartagena" },
  { code: "03", name: "Santa Marta" },
  { code: "04", name: "Riohacha" },
  { code: "05", name: "Valledupar" },
  { code: "06", name: "Montería" },
  { code: "07", name: "Sincelejo" },
  { code: "08", name: "Medellín" },
  { code: "09", name: "Apartadó" },
  { code: "11", name: "Bogotá" },
  { code: "12", name: "Cúcuta" },
  { code: "13", name: "Bucaramanga" },
  { code: "18", name: "Manizales" },
  { code: "19", name: "Pereira" },
  { code: "20", name: "Armenia" },
  { code: "21", name: "Ibagué" },
  { code: "22", name: "Neiva" },
  { code: "24", name: "Cali" },
  { code: "25", name: "Pasto" },
  { code: "26", name: "Popayán" },
  { code: "29", name: "Villavicencio" },
  { code: "32", name: "Tunja" },
];

export const CIIU_COMMON: { code: string; name: string }[] = [
  { code: "0010", name: "Asalariado" },
  { code: "0020", name: "Pensionado" },
  { code: "0090", name: "Rentista de capital" },
  { code: "0111", name: "Cultivo de cereales" },
  { code: "0141", name: "Cría de ganado bovino" },
  { code: "4100", name: "Construcción de edificios" },
  { code: "4711", name: "Comercio al por menor en establecimientos no especializados" },
  { code: "4921", name: "Transporte de pasajeros" },
  { code: "5611", name: "Expendio a la mesa de comidas" },
  { code: "6201", name: "Actividades de desarrollo de sistemas informáticos" },
  { code: "6202", name: "Actividades de consultoría informática" },
  { code: "6412", name: "Bancos comerciales" },
  { code: "6810", name: "Actividades inmobiliarias realizadas con bienes propios" },
  { code: "6820", name: "Actividades inmobiliarias realizadas a cambio de retribución" },
  { code: "6910", name: "Actividades jurídicas" },
  { code: "6920", name: "Actividades de contabilidad y auditoría" },
  { code: "7110", name: "Actividades de arquitectura e ingeniería" },
  { code: "7310", name: "Publicidad" },
  { code: "7490", name: "Otras actividades profesionales, científicas y técnicas" },
  { code: "8511", name: "Educación de la primera infancia" },
  { code: "8521", name: "Educación básica primaria" },
  { code: "8610", name: "Actividades de hospitales y clínicas" },
  { code: "8691", name: "Actividades de apoyo diagnóstico" },
  { code: "9007", name: "Otras actividades de entretenimiento" },
  { code: "9529", name: "Mantenimiento y reparación de otros efectos personales" },
];

export const NAV = [
  { to: "/", label: "Tablero", hint: "Resumen del año gravable" },
  { to: "/topes", label: "¿Debo declarar?", hint: "Arts. 592 a 594-3" },
  { to: "/declaracion", label: "Declaración", hint: "Cédulas del 210" },
  { to: "/cedulas", label: "Matriz cedular", hint: "INCR, exentas, 40 %" },
  { to: "/documentos", label: "Soportes", hint: "Pedir, auditar, normas" },
  { to: "/liquidacion", label: "Liquidación", hint: "Impuesto y saldo" },
  { to: "/formulario", label: "Formulario 210", hint: "Vista del formulario" },
  { to: "/calendario", label: "Calendario", hint: "Vencimientos 2026" },
  { to: "/biblioteca", label: "Normativa", hint: "Índice del E.T. y corpus 210" },
  { to: "/asistente", label: "Asistente", hint: "Consulta sobre la norma" },
] as const;
