export interface CatalogItem {
  code: string;
  name: string;
  isCustom?: boolean;
}

/**
 * Catálogo Oficial de Direcciones Seccionales DIAN (Resolución DIAN 000065 de 2021 y Casilla 12 RUT).
 */
export const DEFAULT_SECCIONALES: CatalogItem[] = [
  { code: "01", name: "Armenia" },
  { code: "02", name: "Barranquilla" },
  { code: "03", name: "Bogotá Aduanas (Eldorado)" },
  { code: "04", name: "Bucaramanga" },
  { code: "05", name: "Cali" },
  { code: "06", name: "Cartagena" },
  { code: "07", name: "Cúcuta" },
  { code: "08", name: "Florencia" },
  { code: "09", name: "Girardot" },
  { code: "10", name: "Ibagué" },
  { code: "11", name: "Medellín" },
  { code: "12", name: "Montería" },
  { code: "13", name: "Neiva" },
  { code: "14", name: "Pasto" },
  { code: "15", name: "Palmira" },
  { code: "16", name: "Pereira" },
  { code: "17", name: "Popayán" },
  { code: "18", name: "Quibdó" },
  { code: "19", name: "Santa Marta" },
  { code: "20", name: "Sincelejo" },
  { code: "21", name: "Sogamoso" },
  { code: "22", name: "San Andrés" },
  { code: "23", name: "Tuluá" },
  { code: "24", name: "Tumaco" },
  { code: "25", name: "Tunja" },
  { code: "26", name: "Valledupar" },
  { code: "27", name: "Villavicencio" },
  { code: "28", name: "Yopal" },
  { code: "31", name: "Bogotá - Grandes Contribuyentes" },
  { code: "32", name: "Bogotá - Personas Jurídicas" },
  { code: "33", name: "Buenaventura" },
  { code: "34", name: "Barrancabermeja" },
  { code: "35", name: "Urabá / Apartadó" },
  { code: "36", name: "Maicao" },
  { code: "37", name: "Ipiales" },
  { code: "38", name: "Pamplona" },
  { code: "39", name: "Arauca" },
  { code: "40", name: "Inírida" },
  { code: "41", name: "Mitú" },
  { code: "42", name: "Puerto Carreño" },
  { code: "43", name: "San José del Guaviare" },
  { code: "44", name: "Leticia" },
  { code: "45", name: "Puerto Asís / Mocoa" },
  { code: "46", name: "Riohacha" },
  { code: "87", name: "Bogotá - Personas Naturales" },
];

/** Alias compatible con código existente */
export const SECCIONALES = DEFAULT_SECCIONALES;

/**
 * Catálogo Oficial de Actividades Económicas CIIU (Casilla 24 RUT - DIAN / DANE Rev. 4 A.C.).
 */
export const DEFAULT_CIIU_COMMON: CatalogItem[] = [
  { code: "0010", name: "Asalariado" },
  { code: "0020", name: "Pensionado" },
  { code: "0090", name: "Rentista de capital" },
  { code: "0111", name: "Cultivo de cereales" },
  { code: "0112", name: "Cultivo de arroz" },
  { code: "0113", name: "Cultivo de hortalizas y legumbres" },
  { code: "0114", name: "Cultivo de tabaco" },
  { code: "0121", name: "Cultivo de café" },
  { code: "0122", name: "Cultivo de plátano y banano" },
  { code: "0123", name: "Cultivo de caña de azúcar" },
  { code: "0124", name: "Cultivo de palma para aceite (palma africana)" },
  { code: "0125", name: "Cultivo de flores y follajes" },
  { code: "0141", name: "Cría de ganado bovino y bufalino" },
  { code: "0142", name: "Cría de caballos y otros equinos" },
  { code: "0143", name: "Cría de ganado porcino" },
  { code: "0144", name: "Cría de aves de corral" },
  { code: "0149", name: "Cría de otros animales vivos" },
  { code: "0311", name: "Pesca marítima" },
  { code: "0321", name: "Acuicultura marítima y continental" },
  { code: "1011", name: "Procesamiento y conservación de carne" },
  { code: "1081", name: "Elaboración de productos de panadería" },
  { code: "1410", name: "Confección de prendas de vestir" },
  { code: "3312", name: "Mantenimiento y reparación especializado de maquinaria y equipo" },
  { code: "3314", name: "Mantenimiento y reparación de equipo eléctrico" },
  { code: "3319", name: "Mantenimiento y reparación de otros tipos de equipo" },
  { code: "4100", name: "Construcción de edificios residenciales y no residenciales" },
  { code: "4210", name: "Construcción de carreteras y vías de ferrocarril" },
  { code: "4321", name: "Instalaciones eléctricas" },
  { code: "4330", name: "Terminación y acabado de edificios y obras de ingeniería" },
  { code: "4511", name: "Comercio de vehículos automotores nuevos" },
  { code: "4520", name: "Mantenimiento y reparación de vehículos automotores" },
  { code: "4610", name: "Comercio al por mayor a cambio de retribución o por contrata" },
  { code: "4620", name: "Comercio al por mayor de materias primas agropecuarias" },
  { code: "4631", name: "Comercio al por mayor de productos alimenticios" },
  { code: "4711", name: "Comercio al por menor en establecimientos no especializados (Supermercados)" },
  { code: "4721", name: "Comercio al por menor de alimentos y bebidas" },
  { code: "4731", name: "Comercio al por menor de combustible para automotores (Estaciones)" },
  { code: "4771", name: "Comercio al por menor de prendas de vestir y calzado" },
  { code: "4921", name: "Transporte de pasajeros urbano e intermunicipal" },
  { code: "4923", name: "Transporte de carga por carretera" },
  { code: "5310", name: "Actividades postales nacionales" },
  { code: "5611", name: "Expendio a la mesa de comidas preparadas (Restaurantes)" },
  { code: "5613", name: "Expendio de comidas preparadas en cafeterías y autoservicio" },
  { code: "5630", name: "Expendio de bebidas alcohólicas para consumo en el local (Bares)" },
  { code: "6110", name: "Actividades de telecomunicaciones alámbricas" },
  { code: "6120", name: "Actividades de telecomunicaciones inalámbricas" },
  { code: "6201", name: "Actividades de desarrollo de sistemas informáticos y software" },
  { code: "6202", name: "Actividades de consultoría informática y TI" },
  { code: "6209", name: "Otras actividades de tecnologías de información y computación" },
  { code: "6412", name: "Bancos comerciales y entidades financieras" },
  { code: "6612", name: "Corretaje de valores y contratos de productos básicos" },
  { code: "6810", name: "Actividades inmobiliarias realizadas con bienes propios o arrendados" },
  { code: "6820", name: "Actividades inmobiliarias a cambio de una retribución (Inmobiliarias)" },
  { code: "6910", name: "Actividades jurídicas (Abogados y asesoría legal)" },
  { code: "6920", name: "Actividades de contabilidad, teneduría de libros, auditoría y tributaria" },
  { code: "7020", name: "Actividades de consultoría de gestión empresarial" },
  { code: "7110", name: "Actividades de arquitectura e ingeniería y consultoría técnica" },
  { code: "7120", name: "Ensayos y análisis técnicos" },
  { code: "7310", name: "Publicidad y mercadeo" },
  { code: "7410", name: "Actividades especializadas de diseño (gráfico, modas, industrial)" },
  { code: "7490", name: "Otras actividades profesionales, científicas y técnicas n.c.p." },
  { code: "8511", name: "Educación de la primera infancia" },
  { code: "8521", name: "Educación básica primaria" },
  { code: "8522", name: "Educación básica secundaria y media" },
  { code: "8544", name: "Educación universitaria y tecnológica" },
  { code: "8610", name: "Actividades de hospitales y clínicas" },
  { code: "8621", name: "Actividades de la práctica médica, sin internación (Consultorios)" },
  { code: "8622", name: "Actividades de la práctica odontológica" },
  { code: "8691", name: "Actividades de apoyo diagnóstico (Laboratorios clínicos)" },
  { code: "9007", name: "Otras actividades de espectáculos en vivo y entretenimiento" },
  { code: "9311", name: "Gestión de instalaciones deportivas (Gimnasios y canchas)" },
  { code: "9529", name: "Mantenimiento y reparación de efectos personales y electrodomésticos" },
  { code: "9602", name: "Peluquería y otros tratamientos de belleza" },
];

/** Alias compatible con código existente */
export const CIIU_COMMON = DEFAULT_CIIU_COMMON;

export const NAV = [
  { to: "/", label: "Panel Principal", hint: "Resumen y estado de la declaración" },
  { to: "/clientes", label: "Gestor de Clientes", hint: "Portafolio y declaraciones guardadas" },
  { to: "/topes", label: "1. Diagnóstico de Topes", hint: "Obligados según Arts. 592 a 594-3" },
  { to: "/documentos", label: "2. Soportes y Documentos", hint: "Carga de certificados, exógena y auditoría" },
  { to: "/declaracion", label: "3. Diligenciamiento 210", hint: "Captura de patrimonio, deudas e ingresos" },
  { to: "/cedulas", label: "4. Depuración Cedular", hint: "Salud, pensión, exenciones y límite del 40 %" },
  { to: "/liquidacion", label: "5. Liquidación y Anticipos", hint: "Cálculo de impuesto, retenciones y saldos" },
  { to: "/formulario", label: "6. Formulario 210 DIAN", hint: "Hoja oficial DIAN, XML Muisca y Excel" },
  { to: "/calendario", label: "Calendario Tributario", hint: "Vencimientos oficiales DIAN 2026" },
  { to: "/biblioteca", label: "Estatuto Tributario", hint: "Artículos oficiales y doctrina DIAN" },
  { to: "/asistente", label: "Asistente IA Gemini", hint: "Copiloto tributario inteligente" },
] as const;
