/**
 * Diccionario Oficial del Instructivo DIAN para el Formulario 210
 * Declaración de Renta y Complementario de Personas Naturales y Asimiladas
 * Con lenguaje claro, profesional y comprensible para cualquier contribuyente.
 */

export interface OperadorCasilla {
  num: number;
  op: "+" | "-";
  labelOverride?: string;
}

export interface FormulaExplicada {
  formula: string;
  descripcion: string;
  casillasInvolucradas: number[];
  operadores?: OperadorCasilla[];
  ejemploCalculo?: (casillas: Record<number, number>) => string;
}

export const FORMULAS_EXPLICADAS_210: Record<number, FormulaExplicada> = {
  31: {
    formula: "Casilla 29 (Bienes y patrimonio bruto) - Casilla 30 (Deudas y créditos pendientes)",
    descripcion: "Es el valor real de tu patrimonio limpio al 31 de diciembre. Se calcula tomando todos tus bienes (casas, apartamentos, vehículos, cuentas bancarias, inversiones) y restando todas tus deudas y créditos financieros pendientes de pago.",
    casillasInvolucradas: [29, 30],
    operadores: [
      { num: 29, op: "+" },
      { num: 30, op: "-" },
    ],
  },
  34: {
    formula: "Casilla 32 (Salarios y pagos laborales) - Casilla 33 (Aportes obligatorios a Salud y Pensión)",
    descripcion: "Total de salarios, prestaciones sociales, bonificaciones y pagos laborales recibidos en el año, menos los descuentos obligatorios de seguridad social (salud, pensión y ARL). El resultado son tus ingresos netos de trabajo sobre los cuales se liquidan tus deducciones.",
    casillasInvolucradas: [32, 33],
    operadores: [
      { num: 32, op: "+" },
      { num: 33, op: "-" },
    ],
  },
  37: {
    formula: "Casilla 35 (Aportes voluntarios FVP y cuentas AFC) + Casilla 36 (Exención del 25% laboral y cesantías)",
    descripcion: "Suma de todos tus beneficios por rentas exentas en trabajo: ahorros voluntarios en fondos de pensiones voluntarias o cuentas AFC, más el 25% de exención laboral automática que otorga la ley (hasta 790 UVT) y cesantías exentas.",
    casillasInvolucradas: [35, 36],
    operadores: [
      { num: 35, op: "+" },
      { num: 36, op: "+" },
    ],
  },
  40: {
    formula: "Casilla 38 (Intereses de vivienda) + Casilla 39 (Medicina prepagada, 50% 4x1000 GMF e ICETEX)",
    descripcion: "Gastos personales permitidos que disminuyen tu base de impuesto: intereses pagados por crédito hipotecario o leasing de vivienda (hasta 1.200 UVT), medicina prepagada o pólizas de salud (hasta 192 UVT), intereses de crédito ICETEX (hasta 100 UVT) y el 50% del impuesto del 4x1000 bancario.",
    casillasInvolucradas: [38, 39],
    operadores: [
      { num: 38, op: "+" },
      { num: 39, op: "+" },
    ],
  },
  41: {
    formula: "Mínimo entre: (Casilla 37 Total exentas + Casilla 40 Total deducciones) y el límite conjunto del 40% de ingresos netos de la Cédula General (tope máximo 1.340 UVT)",
    descripcion: "Paso a paso legal (Art. 336 E.T.): 1. Sumas tus rentas exentas (Casilla 37) y deducciones (Casilla 40). 2. Calculas el 40% sobre los ingresos netos de la Cédula General (máximo 1.340 UVT). 3. Si tus beneficios solicitados son menores a dicho límite, la ley te acepta el 100% sin ningún recorte.",
    casillasInvolucradas: [37, 40],
    operadores: [
      { num: 37, op: "+" },
      { num: 40, op: "+" },
    ],
  },
  42: {
    formula: "Casilla 34 (Ingresos netos de trabajo) - Casilla 41 (Exentas y deducciones aceptadas)",
    descripcion: "Es la ganancia neta depurada de tu trabajo que pasa a integrarse a la Cédula General.",
    casillasInvolucradas: [34, 41],
    operadores: [
      { num: 34, op: "+" },
      { num: 41, op: "-" },
    ],
  },
  46: {
    formula: "Casilla 43 (Honorarios y servicios cobrados) - Casilla 44 (Devoluciones) - Casilla 45 (Aportes a Salud y Pensión como independiente)",
    descripcion: "Total de ingresos recibidos por honorarios o servicios profesionales independientes, menos devoluciones y menos tus aportes obligatorios a salud, pensión y ARL pagados durante el año.",
    casillasInvolucradas: [43, 44, 45],
    operadores: [
      { num: 43, op: "+" },
      { num: 44, op: "-" },
      { num: 45, op: "-" },
    ],
  },
  49: {
    formula: "Casilla 47 (Aportes voluntarios FVP/AFC) + Casilla 48 (Otras rentas exentas en honorarios)",
    descripcion: "Total de beneficios exentos aplicables a la subcédula de honorarios y servicios personales.",
    casillasInvolucradas: [47, 48],
    operadores: [
      { num: 47, op: "+" },
      { num: 48, op: "+" },
    ],
  },
  52: {
    formula: "Casilla 50 (Intereses de vivienda) + Casilla 51 (Medicina prepagada y 50% 4x1000)",
    descripcion: "Total de deducciones personales imputables a tus ingresos por honorarios y servicios.",
    casillasInvolucradas: [50, 51],
    operadores: [
      { num: 50, op: "+" },
      { num: 51, op: "+" },
    ],
  },
  53: {
    formula: "Mínimo entre: (Casilla 49 Total exentas + Casilla 52 Total deducciones) y (Límite del 40% de ingresos o 1.340 UVT)",
    descripcion: "Beneficios y deducciones aceptados en honorarios bajo el tope legal del 40% y 1.340 UVT.",
    casillasInvolucradas: [49, 52],
    operadores: [
      { num: 49, op: "+" },
      { num: 52, op: "+" },
    ],
  },
  54: {
    formula: "Casilla 46 (Ingresos netos por honorarios) - Casilla 53 (Exentas y deducciones aceptadas)",
    descripcion: "Renta líquida ordinaria del ejercicio generada en la subcédula de honorarios y servicios personales antes de compensar pérdidas de años anteriores.",
    casillasInvolucradas: [46, 53],
    operadores: [
      { num: 46, op: "+" },
      { num: 53, op: "-" },
    ],
  },
  57: {
    formula: "Casilla 54 (Renta líquida del ejercicio) - Casilla 56 (Pérdidas de años anteriores)",
    descripcion: "Ganancia neta depurada final de honorarios que se integra a la Cédula General.",
    casillasInvolucradas: [54, 56],
    operadores: [
      { num: 54, op: "+" },
      { num: 56, op: "-" },
    ],
  },
  61: {
    formula: "Casilla 58 (Ingresos brutos capital) - Casilla 59 (Beneficio de inflación y seguridad social) - Casilla 60 (Costos procedentes)",
    descripcion: "Ingresos netos de capital después de restar beneficios no gravados como el componente inflacionario bancario, aportes de seguridad social y costos deducibles.",
    casillasInvolucradas: [58, 59, 60],
    operadores: [
      { num: 58, op: "+" },
      { num: 59, op: "-" },
      { num: 60, op: "-" },
    ],
  },
  65: {
    formula: "Casilla 63 (Aportes voluntarios AFC/FVP) + Casilla 64 (Otras rentas exentas de capital)",
    descripcion: "Total de rentas exentas imputables a tus ingresos por rentas de capital.",
    casillasInvolucradas: [63, 64],
    operadores: [
      { num: 63, op: "+" },
      { num: 64, op: "+" },
    ],
  },
  68: {
    formula: "Casilla 66 (Intereses de vivienda) + Casilla 67 (Otras deducciones / 50% 4x1000 GMF)",
    descripcion: "Total de deducciones imputables a la subcédula de rentas de capital (intereses de crédito hipotecario, deducción del 50% del 4x1000 bancario, etc.).",
    casillasInvolucradas: [66, 67],
    operadores: [
      { num: 66, op: "+" },
      { num: 67, op: "+" },
    ],
  },
  69: {
    formula: "Mínimo entre: (Casilla 65 Total exentas + Casilla 68 Total deducciones) y (Límite del 40% de ingresos netos o 1.340 UVT)",
    descripcion: "Beneficios y deducciones aceptados en rentas de capital bajo el límite conjunto del 40% y 1.340 UVT.",
    casillasInvolucradas: [65, 68],
    operadores: [
      { num: 65, op: "+" },
      { num: 68, op: "+" },
    ],
  },
  70: {
    formula: "Casilla 61 (Ingresos netos) + Casilla 62 (Rentas del exterior ECE) - Casilla 69 (Exentas y deducciones aceptadas)",
    descripcion: "Renta líquida ordinaria del ejercicio generada en rentas de capital antes de compensar pérdidas.",
    casillasInvolucradas: [61, 62, 69],
    operadores: [
      { num: 61, op: "+" },
      { num: 62, op: "+" },
      { num: 69, op: "-" },
    ],
  },
  73: {
    formula: "Casilla 70 (Renta líquida del ejercicio) - Casilla 72 (Pérdidas fiscales anteriores)",
    descripcion: "Ganancia neta depurada de rentas de capital que se integra a la Cédula General.",
    casillasInvolucradas: [70, 72],
    operadores: [
      { num: 70, op: "+" },
      { num: 72, op: "-" },
    ],
  },
  78: {
    formula: "Casilla 74 (Ventas e ingresos del negocio) - Casilla 75 (Devoluciones) - Casilla 76 (Seguridad social) - Casilla 77 (Costos y gastos procedentes del negocio)",
    descripcion: "Ingresos por actividades comerciales, agropecuarias, manufactura o servicios con costos, restando todas las compras de mercancía, insumos, nóminas y gastos necesarios para producir la renta.",
    casillasInvolucradas: [74, 75, 76, 77],
    operadores: [
      { num: 74, op: "+" },
      { num: 75, op: "-" },
      { num: 76, op: "-" },
      { num: 77, op: "-" },
    ],
  },
  82: {
    formula: "Casilla 80 (Aportes voluntarios AFC/FVP) + Casilla 81 (Otras rentas exentas no laborales)",
    descripcion: "Total de rentas exentas imputables a tus actividades comerciales o de negocio.",
    casillasInvolucradas: [80, 81],
    operadores: [
      { num: 80, op: "+" },
      { num: 81, op: "+" },
    ],
  },
  85: {
    formula: "Casilla 83 (Intereses de vivienda) + Casilla 84 (Otras deducciones / 50% 4x1000 GMF)",
    descripcion: "Total de deducciones aplicables a actividades comerciales y no laborales.",
    casillasInvolucradas: [83, 84],
    operadores: [
      { num: 83, op: "+" },
      { num: 84, op: "+" },
    ],
  },
  86: {
    formula: "Mínimo entre: (Casilla 82 Total exentas + Casilla 85 Total deducciones) y (Límite del 40% o 1.340 UVT)",
    descripcion: "Beneficios tributarios aceptados en actividades comerciales y no laborales bajo el límite del 40% y 1.340 UVT.",
    casillasInvolucradas: [82, 85],
    operadores: [
      { num: 82, op: "+" },
      { num: 85, op: "+" },
    ],
  },
  87: {
    formula: "Casilla 78 (Ingresos netos) + Casilla 79 (Rentas del exterior ECE) - Casilla 86 (Exentas y deducciones aceptadas)",
    descripcion: "Renta líquida ordinaria del ejercicio en actividades no laborales antes de compensar pérdidas.",
    casillasInvolucradas: [78, 79, 86],
    operadores: [
      { num: 78, op: "+" },
      { num: 79, op: "+" },
      { num: 86, op: "-" },
    ],
  },
  90: {
    formula: "Casilla 87 (Renta líquida del ejercicio) - Casilla 89 (Pérdidas fiscales anteriores)",
    descripcion: "Ganancia neta depurada final de actividades comerciales y no laborales que se integra a la Cédula General.",
    casillasInvolucradas: [87, 89],
    operadores: [
      { num: 87, op: "+" },
      { num: 89, op: "-" },
    ],
  },
  91: {
    formula: "Casilla 34 (Trabajo) + Casilla 46 (Honorarios) + Casilla 61 (Capital) + Casilla 62 (ECE) + Casilla 78 (No Laborales) + Casilla 79 (ECE)",
    descripcion: "Sumatoria de todos los ingresos netos recibidos en el año por todas tus fuentes de ingresos (salarios, honorarios, arriendos, rendimientos bancarios y negocios).",
    casillasInvolucradas: [34, 46, 61, 62, 78, 79],
    operadores: [
      { num: 34, op: "+" },
      { num: 46, op: "+" },
      { num: 61, op: "+" },
      { num: 62, op: "+" },
      { num: 78, op: "+" },
      { num: 79, op: "+" },
    ],
  },
  92: {
    formula: "Casilla 41 (Trabajo) + Casilla 53 (Honorarios) + Casilla 69 (Capital) + Casilla 86 (No Laborales) + Casilla 139 (Dependientes) + Casilla 28 (1% Factura Electrónica)",
    descripcion: "Total consolidado de todos los beneficios y deducciones aplicados en tus subcédulas (limitadas al 40% o 1.340 UVT), más los beneficios adicionales sin límite: 72 UVT por cada dependiente económico (hasta 4) y el 1% de compras soportadas con Factura Electrónica.",
    casillasInvolucradas: [41, 53, 69, 86, 139, 28],
    operadores: [
      { num: 41, op: "+" },
      { num: 53, op: "+" },
      { num: 69, op: "+" },
      { num: 86, op: "+" },
      { num: 139, op: "+" },
      { num: 28, op: "+" },
    ],
  },
  93: {
    formula: "Casilla 91 (Ingresos netos Cédula General) - Casilla 92 (Total rentas exentas y deducciones imputables)",
    descripcion: "Renta líquida ordinaria de la Cédula General. Se calcula tomando los ingresos netos totales de todas las subcédulas (Casilla 91) y restando el total de beneficios y deducciones imputables aceptados (Casilla 92: beneficios del 40%, deducción 72 UVT por dependiente y 1% de factura electrónica).",
    casillasInvolucradas: [91, 92],
    operadores: [
      { num: 91, op: "+" },
      { num: 92, op: "-" },
    ],
  },
  97: {
    formula: "Mayor entre (0, Casilla 93 Renta ordinaria - Casilla 94 Pérdidas anteriores - Casilla 95 Exceso presuntiva + Casilla 96 Rentas gravables)",
    descripcion: "Es la base imponible definitiva sobre la que se calculará tu impuesto de renta de la Cédula General aplicando la tabla progresiva de tarifas oficiales del Artículo 241 del Estatuto Tributario.",
    casillasInvolucradas: [93, 94, 95, 96],
    operadores: [
      { num: 93, op: "+" },
      { num: 94, op: "-" },
      { num: 95, op: "-" },
      { num: 96, op: "+" },
    ],
  },
  101: {
    formula: "Casilla 99 (Mesadas pensionales del año) - Casilla 100 (Descuentos obligatorios de salud y Fondo de Solidaridad)",
    descripcion: "Total de pensiones de jubilación, vejez, invalidez o sobrevivientes recibidas, menos los descuentos obligatorios de salud.",
    casillasInvolucradas: [99, 100],
    operadores: [
      { num: 99, op: "+" },
      { num: 100, op: "-" },
    ],
  },
  103: {
    formula: "Máximo entre (0, Casilla 101 Ingresos netos pensiones - Casilla 102 Exención de hasta 1.000 UVT mensuales)",
    descripcion: "En Colombia las pensiones de hasta 1.000 UVT al mes están 100% exentas de impuestos (Art. 206 numeral 5 E.T.). Si no superas este monto, tu renta gravable de pensiones es $0.",
    casillasInvolucradas: [101, 102],
    operadores: [
      { num: 101, op: "+" },
      { num: 102, op: "-" },
    ],
  },
  106: {
    formula: "Casilla 104 (Dividendos utilidades 2016 y anteriores) - Casilla 105 (Dividendos no gravados 2016)",
    descripcion: "Ganancia neta ordinaria de dividendos provenientes de utilidades generadas en 2016 y periodos anteriores.",
    casillasInvolucradas: [104, 105],
    operadores: [
      { num: 104, op: "+" },
      { num: 105, op: "-" },
    ],
  },
  111: {
    formula: "Mayor entre (Casilla 97 Renta gravable y Casilla 98 Renta presuntiva) + Casilla 103 (Pensiones gravables) + Casilla 107 (Dividendos 1ª subcédula) + Casilla 109 (Dividendos exterior) - Casilla 110 (Exentas exterior)",
    descripcion: "Base gravable consolidada de todas tus rentas sobre la cual se aplica la tabla de tarifas progresivas de impuesto de renta (Art. 241 E.T.).",
    casillasInvolucradas: [97, 103, 107, 109, 110],
    operadores: [
      { num: 97, op: "+" },
      { num: 103, op: "+" },
      { num: 107, op: "+" },
      { num: 109, op: "+" },
      { num: 110, op: "-" },
    ],
  },
  115: {
    formula: "Casilla 112 (Ingresos por venta de inmuebles/herencias/loterías) - Casilla 113 (Costo fiscal del bien) - Casilla 114 (Ganancias exentas)",
    descripcion: "Ganancia limpia por venta de casas, apartamentos o vehículos poseídos por más de 2 años, herencias, donaciones o premios, sobre la cual se aplica la tarifa del 15% (o 20% para loterías y rifas).",
    casillasInvolucradas: [112, 113, 114],
    operadores: [
      { num: 112, op: "+" },
      { num: 113, op: "-" },
      { num: 114, op: "-" },
    ],
  },
  116: {
    formula: "Tabla de tarifas progresivas del Artículo 241 del Estatuto Tributario aplicada sobre la Casilla 111",
    descripcion: "Impuesto determinado según los 7 tramos de tarifas en UVT (los primeros 1.090 UVT pagan 0%, luego 19%, 28%, 33%, 35%, 37% y 39%).",
    casillasInvolucradas: [111],
  },
  118: {
    formula: "35% sobre la Casilla 108 (Dividendos y participaciones gravados a la tarifa general del Art. 240 E.T.)",
    descripcion: "Impuesto generado sobre dividendos recibidos de sociedades que no fueron gravados en cabeza de la sociedad.",
    casillasInvolucradas: [108],
  },
  121: {
    formula: "Casilla 116 (Impuesto Cédula General y Pensiones) + Casilla 117 (Impuesto Renta Presuntiva) + Casilla 118 (Impuesto Dividendos 35%) + Casilla 119 + Casilla 120",
    descripcion: "Suma de los impuestos calculados sobre tus rentas ordinarias y dividendos antes de aplicar descuentos tributarios.",
    casillasInvolucradas: [116, 117, 118, 119, 120],
    operadores: [
      { num: 116, op: "+" },
      { num: 117, op: "+" },
      { num: 118, op: "+" },
      { num: 119, op: "+" },
      { num: 120, op: "+" },
    ],
  },
  125: {
    formula: "Casilla 122 (Impuestos pagados en el exterior) + Casilla 123 (Descuento del 25% por donaciones a fundaciones/ESAL) + Casilla 124 (Otros descuentos)",
    descripcion: "Descuentos que se restan directamente peso a peso del impuesto liquidado a pagar.",
    casillasInvolucradas: [122, 123, 124],
    operadores: [
      { num: 122, op: "+" },
      { num: 123, op: "+" },
      { num: 124, op: "+" },
    ],
  },
  126: {
    formula: "Máximo entre (0, Casilla 121 Total impuesto - Casilla 125 Descuentos tributarios)",
    descripcion: "Impuesto neto de renta después de restar tus descuentos tributarios por donaciones o pagos en el exterior.",
    casillasInvolucradas: [121, 125],
    operadores: [
      { num: 121, op: "+" },
      { num: 125, op: "-" },
    ],
  },
  127: {
    formula: "15% sobre Casilla 115 (o 20% para loterías, rifas y apuestas)",
    descripcion: "Impuesto generado por ganancias ocasionales (venta de bienes raíces, vehículos antiguos, herencias o premios).",
    casillasInvolucradas: [115],
  },
  129: {
    formula: "Casilla 126 (Impuesto neto de renta) + Casilla 127 (Impuesto de ganancias ocasionales) - Casilla 128 (Descuento exterior GO)",
    descripcion: "Monto total del impuesto que te corresponde asumir por el año gravable antes de restar tus retenciones en la fuente y anticipos.",
    casillasInvolucradas: [126, 127, 128],
    operadores: [
      { num: 126, op: "+" },
      { num: 127, op: "+" },
      { num: 128, op: "-" },
    ],
  },
  134: {
    formula: "Casilla 129 (Impuesto a cargo) - Casilla 130 (Anticipo año anterior) - Casilla 131 (Saldo a favor anterior) - Casilla 132 (Retenciones que te practicaron) + Casilla 133 (Anticipo año siguiente)",
    descripcion: "Saldo de impuesto pendiente por pagar una vez cruzadas las retenciones en la fuente y anticipos previos.",
    casillasInvolucradas: [129, 130, 131, 132, 133],
    operadores: [
      { num: 129, op: "+" },
      { num: 133, op: "+" },
      { num: 130, op: "-" },
      { num: 131, op: "-" },
      { num: 132, op: "-" },
    ],
  },
  136: {
    formula: "Casilla 129 (Impuesto) + Casilla 133 (Anticipo año siguiente) + Casilla 135 (Sanciones) - Casilla 130 (Anticipo anterior) - Casilla 131 (Saldo a favor anterior) - Casilla 132 (Retenciones)",
    descripcion: "Valor total definitivo que debes pagar en el banco o portal de la DIAN al presentar tu declaración de renta.",
    casillasInvolucradas: [129, 133, 135, 130, 131, 132],
    operadores: [
      { num: 129, op: "+" },
      { num: 133, op: "+" },
      { num: 135, op: "+" },
      { num: 130, op: "-" },
      { num: 131, op: "-" },
      { num: 132, op: "-" },
    ],
  },
  137: {
    formula: "Casilla 130 (Anticipo anterior) + Casilla 131 (Saldo a favor anterior) + Casilla 132 (Retenciones que te practicaron) - Casilla 129 (Impuesto a cargo) - Casilla 133 (Anticipo siguiente) - Casilla 135 (Sanciones)",
    descripcion: "Dinero a tu favor porque tus retenciones y anticipos fueron mayores al impuesto liquidado. Puedes pedirlo en devolución, compensación o arrastrarlo a tu declaración del próximo año.",
    casillasInvolucradas: [130, 131, 132, 129, 133, 135],
    operadores: [
      { num: 130, op: "+" },
      { num: 131, op: "+" },
      { num: 132, op: "+" },
      { num: 129, op: "-" },
      { num: 133, op: "-" },
      { num: 135, op: "-" },
    ],
  },
  139: {
    formula: "Casilla 138 (Número de dependientes económicos) × 72 UVT",
    descripcion: "Deducción especial de 72 UVT por cada dependiente económico certificado (hasta 4 dependientes máximo), permitida por el Art. 336 numeral 2 E.T. sin quedar sujeta al límite conjunto del 40% ni de las 1.340 UVT.",
    casillasInvolucradas: [138],
  },
  980: {
    formula: "Igual a Casilla 136 (Total saldo a pagar en bancos)",
    descripcion: "Valor a pagar en la entidad bancaria autorizada o a través del pago electrónico PSE de la DIAN.",
    casillasInvolucradas: [136],
  },
};

export const CASILLA_NOMBRES_CLAROS: Record<number, string> = {
  1: "Año Gravable declarado",
  4: "Número de formulario único",
  5: "Número de Identificación Tributaria (NIT / Cédula)",
  6: "Dígito de verificación (DV)",
  7: "Primer apellido",
  8: "Segundo apellido",
  9: "Primer nombre",
  10: "Otros nombres",
  12: "Dirección Seccional DIAN",
  24: "Actividad económica principal CIIU",
  25: "Código de corrección",
  26: "Número de formulario anterior que se corrige",
  27: "Fracción de año gravable siguiente",
  28: "1% Compras con Factura Electrónica (Deducción adicional)",
  29: "Patrimonio bruto (Total de bienes y derechos)",
  30: "Deudas y obligaciones financieras pendientes",
  31: "Patrimonio líquido (Bienes menos deudas)",
  32: "Salarios, prestaciones y pagos laborales",
  33: "Aportes obligatorios a Salud y Pensión",
  34: "Ingresos netos de trabajo",
  35: "Aportes voluntarios a pensiones (FVP) y cuentas AFC",
  36: "Exención del 25% laboral y cesantías",
  37: "Total rentas exentas de trabajo",
  38: "Intereses de crédito hipotecario o leasing de vivienda",
  39: "Medicina prepagada, 50% 4x1000 GMF e ICETEX",
  40: "Total deducciones de trabajo",
  41: "Rentas exentas y deducciones aceptadas (Límite 40% / 1.340 UVT)",
  42: "Renta líquida ordinaria de trabajo",
  43: "Honorarios y compensación de servicios recibidos",
  44: "Devoluciones en honorarios",
  45: "Aportes a Salud y Pensión como independiente",
  46: "Ingresos netos por honorarios",
  47: "Aportes voluntarios AFC/FVP en honorarios",
  48: "Otras rentas exentas en honorarios",
  49: "Total rentas exentas en honorarios",
  50: "Intereses de vivienda en honorarios",
  51: "Otras deducciones en honorarios",
  52: "Total deducciones en honorarios",
  53: "Exentas y deducciones aceptadas en honorarios",
  54: "Renta líquida del ejercicio en honorarios",
  55: "Pérdida líquida del ejercicio en honorarios",
  56: "Pérdidas fiscales compensadas en honorarios",
  57: "Renta líquida ordinaria de honorarios",
  58: "Ingresos brutos por rentas de capital (Intereses, rendimientos, arriendos)",
  59: "Ingresos no constitutivos de renta (Componente inflacionario y seguridad social)",
  60: "Costos y deducciones procedentes de capital",
  61: "Renta líquida de capital",
  62: "Rentas líquidas pasivas - ECE de capital",
  63: "Aportes voluntarios AFC / FVP en capital",
  64: "Otras rentas exentas de capital",
  65: "Total rentas exentas de capital",
  66: "Intereses de crédito de vivienda en capital",
  67: "Otras deducciones imputables en capital",
  68: "Total deducciones imputables en capital",
  69: "Rentas exentas y deducciones aceptadas en capital (Límite 40% / 1.340 UVT)",
  70: "Renta líquida ordinaria del ejercicio en capital",
  71: "Pérdida líquida del ejercicio en capital",
  72: "Compensación por pérdidas en capital",
  73: "Renta líquida ordinaria de capital",
  74: "Ventas e ingresos brutos del negocio o actividad",
  75: "Devoluciones en ventas",
  76: "Aportes a seguridad social del negocio",
  77: "Costos y gastos procedentes de la actividad",
  78: "Ingresos netos de actividades no laborales",
  79: "Rentas pasivas del exterior (ECE) no laborales",
  80: "Aportes voluntarios AFC/FVP en no laborales",
  81: "Otras rentas exentas no laborales",
  82: "Total rentas exentas no laborales",
  83: "Intereses de vivienda en no laborales",
  84: "Otras deducciones no laborales",
  85: "Total deducciones no laborales",
  86: "Exentas y deducciones aceptadas no laborales",
  87: "Renta líquida del ejercicio no laboral",
  88: "Pérdida líquida del ejercicio no laboral",
  89: "Pérdidas fiscales compensadas no laborales",
  90: "Renta líquida ordinaria no laboral",
  91: "Total ingresos netos de la Cédula General",
  92: "Total beneficios y deducciones de la Cédula General",
  93: "Renta líquida ordinaria de la Cédula General",
  94: "Compensación de pérdidas año 2018 y anteriores",
  95: "Compensación por exceso de renta presuntiva",
  96: "Rentas gravables por activos omitidos o comparación patrimonial",
  97: "Base gravable para impuesto - Cédula General",
  98: "Renta presuntiva (0% vigente)",
  99: "Mesadas pensionales recibidas en el año",
  100: "Aportes a salud sobre pensiones",
  101: "Ingresos netos de pensiones",
  102: "Rentas exentas de pensiones (Hasta 1.000 UVT/mes)",
  103: "Renta gravable de pensiones",
  104: "Dividendos utilidades año 2016 y anteriores",
  105: "Dividendos no gravados 2016",
  106: "Renta ordinaria dividendos 2016",
  107: "Dividendos año 2017+ no gravados en sociedad (Tarifa Art. 242)",
  108: "Dividendos año 2017+ gravados en sociedad (Tarifa Art. 240 - 35%)",
  109: "Dividendos recibidos del exterior",
  110: "Rentas exentas sobre dividendos del exterior",
  111: "Base gravable total consolidada (Art. 241)",
  112: "Ingresos por venta de inmuebles/herencias/loterías",
  113: "Costo fiscal de los bienes vendidos",
  114: "Ganancias ocasionales exentas",
  115: "Ganancias ocasionales gravables (Base 15%)",
  116: "Impuesto de renta calculado (Tabla Art. 241)",
  117: "Impuesto sobre renta presuntiva",
  118: "Impuesto por dividendos gravados al 35%",
  119: "Impuesto por dividendos 2016",
  120: "Impuesto por dividendos del exterior",
  121: "Total impuesto sobre la renta",
  122: "Descuento por impuestos pagados en el exterior",
  123: "Descuento del 25% por donaciones a fundaciones/ESAL",
  124: "Otros descuentos tributarios",
  125: "Total descuentos tributarios aplicados",
  126: "Impuesto neto de renta",
  127: "Impuesto de ganancias ocasionales (15% o 20%)",
  128: "Descuento exterior en ganancias ocasionales",
  129: "Total impuesto a cargo",
  130: "Anticipo de renta pagado el año anterior",
  131: "Saldo a favor del año anterior",
  132: "Retenciones en la fuente que te practicaron",
  133: "Anticipo de renta para el año siguiente",
  134: "Saldo neto de impuesto por pagar",
  135: "Sanciones tributarias",
  136: "Total saldo a pagar en bancos",
  137: "Total saldo a favor del contribuyente",
  138: "Número de dependientes económicos (Hasta 4)",
  139: "Deducción adicional por dependientes (72 UVT c/u)",
  140: "¿Costos de independientes superaron el 60%?",
  141: "Aporte voluntario para programas sociales",
  980: "Pago total en bancos",
};

export const INSTRUCTIVO_DIAN_210: Record<number, string> = {
  1: "Año gravable correspondiente a la declaración tributaria. Para el periodo actual corresponde al AG 2024 / 2025.",
  4: "Número de formulario preimpreso asignado oficialmente por la DIAN o autogenerado por el sistema MUISCA.",
  5: "Número de Identificación Tributaria (NIT) o cédula de ciudadanía del declarante, tal como figura en la casilla 5 de la hoja principal del RUT, sin incluir el dígito de verificación.",
  6: "Dígito de verificación (DV) correspondiente al NIT o cédula del declarante (casilla 6 del RUT), calculado mediante el algoritmo oficial del módulo 11 del Estatuto Tributario.",
  7: "Primer apellido del declarante tal como figura en el RUT (casilla 31).",
  8: "Segundo apellido del declarante tal como figura en el RUT (casilla 32).",
  9: "Primer nombre del declarante tal como figura en el RUT (casilla 33).",
  10: "Otros nombres del declarante tal como figura en el RUT (casilla 34).",
  12: "Código de la Dirección Seccional de la DIAN con jurisdicción sobre el domicilio fiscal principal del declarante (casilla 12 del RUT).",
  24: "Código de la actividad económica principal del declarante según la clasificación CIIU Rev. 4 A.C. de la DIAN (casilla 46 del RUT).",
  25: "Código de corrección (1, 2, 3 o 4) según los Artículos 588 y 589 del Estatuto Tributario cuando se presenta una declaración en reemplazo de una anterior.",
  26: "Número de formulario anterior: Escriba el número de adhesivo o radicado de la declaración anterior que se corrige.",
  27: "Fracción de año gravable siguiente: Marque si declara por fracción de año con motivo de liquidación de sucesión ilíquida o cambio de domicilio fiscal.",
  28: "Deducción por compras soportadas con Factura Electrónica (Art. 336 parágrafo 5 E.T.): Corresponde al 1% del valor de las adquisiciones de bienes y servicios pagadas mediante medios electrónicos, sin que exceda de 240 UVT.",
  29: "Total patrimonio bruto: Incluye el valor patrimonial fiscal de todos los bienes y derechos apreciables en dinero poseídos en el país y en el exterior al 31 de diciembre (bienes raíces, vehículos, cuentas bancarias, saldos en fondos de cesantías, acciones, inversiones, inventarios, etc. - Arts. 261 a 281 E.T.).",
  30: "Deudas: Incluye el saldo de las deudas y obligaciones financieras respaldadas con documento idóneo vigentes a 31 de diciembre (Art. 283 E.T.).",
  31: "Total patrimonio líquido: Resultado de restar las deudas (casilla 30) del total patrimonio bruto (casilla 29).",
  32: "Ingresos brutos por rentas de trabajo: Salarios, comisiones, prestaciones sociales, viáticos, gastos de representación, honorarios de empleados y cesantías consignadas o pagadas en el año (Art. 103 E.T.).",
  33: "Ingresos no constitutivos de renta: Aportes obligatorios a salud (Art. 56 E.T.), pensión obligatoria (Art. 55 E.T.) y ARL.",
  34: "Renta líquida de trabajo: Casilla 32 - Casilla 33.",
  35: "Aportes voluntarios a fondos de pensiones voluntarias (FVP) y cuentas AFC/AVC (Art. 126-1 y 126-4 E.T., límite 30% del ingreso y máx 3.800 UVT).",
  36: "Otras rentas exentas de trabajo: Exención del 25% del numeral 10 del Art. 206 E.T. (hasta 790 UVT), cesantías e indemnizaciones exentas.",
  37: "Total rentas exentas de trabajo: Casilla 35 + Casilla 36.",
  38: "Intereses de crédito de vivienda para adquisición de casa de habitación (Art. 119 E.T., hasta 1.200 UVT).",
  39: "Otras deducciones de trabajo: Deducción por dependientes del 10% (Art. 387 E.T.), medicina prepagada (hasta 192 UVT), 50% del GMF (4x1000) e intereses ICETEX (hasta 100 UVT).",
  40: "Total deducciones de trabajo: Casilla 38 + Casilla 39.",
  41: "Rentas exentas y deducciones limitadas de trabajo: Suma de exentas y deducciones que no superan el 40% de la Casilla 34 ni las 1.340 UVT.",
  42: "Renta líquida ordinaria de trabajo: Casilla 34 - Casilla 41.",
  43: "Ingresos brutos por honorarios y compensación de servicios personales independientes no sujetos a costos.",
  44: "Devoluciones, rebajas y descuentos en honorarios y servicios.",
  45: "Ingresos no constitutivos de renta en honorarios (aportes obligatorios de salud y pensión como independiente).",
  46: "Ingresos netos por honorarios y servicios: Casilla 43 - Casilla 44 - Casilla 45.",
  47: "Aportes voluntarios AFC/FVP en honorarios.",
  48: "Otras rentas exentas en honorarios.",
  49: "Total rentas exentas en honorarios: Casilla 47 + Casilla 48.",
  50: "Intereses de vivienda en honorarios (hasta 1.200 UVT).",
  51: "Otras deducciones en honorarios (medicina prepagada, GMF 50%).",
  52: "Total deducciones en honorarios: Casilla 50 + Casilla 51.",
  53: "Rentas exentas y deducciones limitadas en honorarios (límite 40% / 1.340 UVT).",
  54: "Renta líquida ordinaria del ejercicio en honorarios: Casilla 46 - Casilla 53.",
  55: "Pérdida líquida del ejercicio en honorarios.",
  56: "Compensaciones por pérdidas fiscales en honorarios.",
  57: "Renta líquida ordinaria final en honorarios: Casilla 54 - Casilla 56.",
  58: "Ingresos brutos por rentas de capital: Intereses, rendimientos financieros de cuentas/CDT/fondos de cesantías, arrendamientos de bienes muebles/inmuebles y regalías.",
  59: "Ingresos no constitutivos de renta en capital: Componente inflacionario no gravado de rendimientos financieros (Arts. 38 y 40-1 E.T.) y aportes obligatorios a seguridad social.",
  60: "Costos y deducciones procedentes en rentas de capital (Art. 107 E.T.).",
  61: "Renta líquida de capital: Casilla 58 - Casilla 59 - Casilla 60.",
  62: "Rentas líquidas pasivas de Entidades Controladas del Exterior (ECE) en rentas de capital.",
  63: "Aportes voluntarios AFC/FVP en rentas de capital (límite 30% / 3.800 UVT).",
  64: "Otras rentas exentas en rentas de capital.",
  65: "Total rentas exentas en rentas de capital: Casilla 63 + Casilla 64.",
  66: "Intereses de vivienda en rentas de capital (hasta 1.200 UVT).",
  67: "Otras deducciones en rentas de capital (50% del GMF / 4x1000 - Art. 115 E.T., intereses ICETEX, aportes a cesantías de independiente).",
  68: "Total deducciones en rentas de capital: Casilla 66 + Casilla 67.",
  69: "Rentas exentas y deducciones limitadas en rentas de capital (límite 40% / 1.340 UVT).",
  70: "Renta líquida ordinaria del ejercicio en rentas de capital: Casilla 61 + Casilla 62 - Casilla 69.",
  71: "Pérdida líquida del ejercicio en rentas de capital.",
  72: "Compensaciones por pérdidas fiscales en rentas de capital.",
  73: "Renta líquida ordinaria final en rentas de capital: Casilla 70 - Casilla 72.",
  74: "Ingresos brutos no laborales: Comercio, manufactura, servicios con costos procedentes y actividades agropecuarias.",
  75: "Devoluciones, rebajas y descuentos en rentas no laborales.",
  76: "Ingresos no constitutivos de renta en rentas no laborales.",
  77: "Costos y deducciones procedentes en rentas no laborales (cumpliendo requisitos del Art. 107 E.T.).",
  78: "Ingresos netos no laborales: Casilla 74 - Casilla 75 - Casilla 76 - Casilla 77.",
  79: "Rentas líquidas pasivas de Entidades Controladas del Exterior (ECE) en rentas no laborales.",
  80: "Aportes voluntarios AFC/FVP/AVC en rentas no laborales (máx 30% y 3.800 UVT).",
  81: "Otras rentas exentas no laborales (servicios hoteleros exentos consolidados, convenios CAN).",
  82: "Total rentas exentas no laborales: Casilla 80 + Casilla 81.",
  83: "Intereses de vivienda en rentas no laborales (hasta 1.200 UVT).",
  84: "Otras deducciones en rentas no laborales (GMF 50%, etc.).",
  85: "Total deducciones en rentas no laborales: Casilla 83 + Casilla 84.",
  86: "Rentas exentas y deducciones limitadas no laborales (límite 40% / 1.340 UVT).",
  87: "Renta líquida ordinaria del ejercicio no laboral: Casilla 78 + Casilla 79 - Casilla 86.",
  88: "Pérdida líquida del ejercicio no laboral.",
  89: "Compensaciones por pérdidas fiscales en rentas no laborales.",
  90: "Renta líquida ordinaria final no laboral: Casilla 87 - Casilla 89.",
  91: "Renta líquida total de la cédula general: Sumatoria de los ingresos netos de las 4 subcédulas (Casillas 34 + 46 + 61 + 78).",
  92: "Total rentas exentas y deducciones imputables limitadas: Suma de las casillas 41 + 53 + 69 + 86 + 139 (dependientes 72 UVT c/u) + 28 (1% factura electrónica).",
  93: "Renta líquida ordinaria cédula general: Sumatoria de Casillas 42 + 57 + 73 + 90.",
  94: "Compensaciones por pérdidas fiscales declaradas en años gravables 2018 y anteriores (Art. 330 parágrafo E.T.).",
  95: "Compensaciones por excesos de renta presuntiva sobre renta líquida ordinaria de años anteriores (Art. 189 E.T.).",
  96: "Rentas gravables: activos omitidos, pasivos inexistentes (Art. 239-1 E.T.) y renta líquida por comparación patrimonial no justificada.",
  97: "Renta líquida gravable cédula general: Resultado de Casilla 93 + Casilla 96 - Casilla 94 - Casilla 95. Constituye la base para aplicar la tarifa del Art. 241 E.T.",
  98: "Renta presuntiva del año gravable sobre patrimonio líquido del año anterior depurado (tarifa 0% vigente).",
  99: "Ingresos por pensiones de jubilación, invalidez, vejez, sobrevivientes, riesgos laborales y asignaciones de retiro de FFAA (país y exterior).",
  100: "Aportes obligatorios al sistema general de salud y Fondo de Solidaridad Pensional sobre mesadas pensionales.",
  101: "Renta líquida de pensiones: Casilla 99 - Casilla 100.",
  102: "Rentas exentas de pensiones: La parte de los pagos pensionales que no exceda de 1.000 UVT mensuales (Art. 206 num. 5 E.T.).",
  103: "Renta líquida gravable de pensiones: Casilla 101 - Casilla 102.",
  104: "Dividendos y participaciones pagados con utilidades generadas en periodos 2016 y anteriores.",
  105: "Ingresos no constitutivos de renta de dividendos 2016 y anteriores (distribuidos como no gravados según Art. 49 num. 3 E.T.).",
  106: "Renta líquida ordinaria de dividendos año 2016 y anteriores: Casilla 104 - Casilla 105.",
  107: "1ª Subcédula años 2017 y siguientes: Dividendos distribuidos como no gravados en cabeza de la sociedad (Art. 49 num. 3 E.T.), gravados con la tabla del Art. 242 inciso 1 E.T. (integrados en Casilla 111).",
  108: "2ª Subcédula años 2017 y siguientes: Dividendos procedentes de utilidades gravadas en la sociedad (Art. 49 par. 2 E.T.), gravados a la tarifa general del Art. 240 E.T. (35%).",
  109: "Dividendos y participaciones recibidos del exterior o de Entidades Controladas del Exterior (ECE).",
  110: "Rentas exentas sobre dividendos recibidos del exterior (convenios CAN Decisión 578).",
  111: "Base gravable para aplicar la tarifa del Art. 241 E.T.: Mayor valor entre Casilla 97 (Renta gravable) y Casilla 98 (Presuntiva) + Casilla 103 (Pensiones) + Casilla 107 + Casilla 109 - Casilla 110.",
  112: "Ingresos brutos por ganancias ocasionales: venta de activos fijos poseídos 2 años o más, herencias, legados, donaciones, porción conyugal, seguros de vida, loterías y rifas.",
  113: "Costo fiscal de los activos fijos enajenados que originaron la ganancia ocasional.",
  114: "Ganancias ocasionales no gravadas y exentas: primeras 13.000 UVT de vivienda del causante, 3.250 UVT de herencias, 5.000 UVT utilidad venta casa habitación (AFC) y seguros de vida (hasta 3.250 UVT).",
  115: "Ganancias ocasionales gravables: Casilla 112 - Casilla 113 - Casilla 114 (mínimo 0).",
  116: "Impuesto sobre las rentas líquidas gravables: Resultado de aplicar la tabla progresiva del Art. 241 E.T. a la base de la Casilla 111 cuando la renta ordinaria supera la presuntiva.",
  117: "Impuesto liquidado cuando la renta presuntiva es mayor que la renta ordinaria.",
  118: "Impuesto por dividendos 2ª subcédula 2017+ (Art. 240 E.T. al 35% sobre Casilla 108).",
  119: "Impuesto por dividendos gravados año 2016 y anteriores (según tarifas históricas Art. 241).",
  120: "Impuesto por dividendos y participaciones recibidas del exterior gravadas a la tarifa general.",
  121: "Total impuesto sobre las rentas líquidas gravables: Casilla 116 + Casilla 117 + Casilla 118 + Casilla 119 + Casilla 120.",
  122: "Descuento por impuestos pagados en el exterior sobre rentas de fuente extranjera (Art. 254 E.T.).",
  123: "Descuento tributario por donaciones a entidades del Régimen Tributario Especial (ESAL) y no contribuyentes (Art. 257 E.T., 25% del valor donado).",
  124: "Otros descuentos tributarios legalmente autorizados (Art. 254-1 E.T., etc.).",
  125: "Total descuentos tributarios: Casilla 122 + Casilla 123 + Casilla 124 (no pueden exceder el impuesto básico de renta según Art. 259 E.T.).",
  126: "Impuesto neto de renta: Casilla 121 - Casilla 125.",
  127: "Impuesto de ganancias ocasionales: 15% sobre la casilla 115 (o 20% para loterías, rifas y apuestas según Art. 317 E.T.).",
  128: "Descuento por impuestos pagados en el exterior imputables a ganancias ocasionales (Art. 254 E.T.).",
  129: "Total impuesto a cargo: Casilla 126 + Casilla 127 - Casilla 128.",
  130: "Anticipo de renta liquidado en el año gravable anterior para el presente periodo fiscal (Art. 807 E.T.).",
  131: "Saldo a favor del año gravable anterior sin solicitud de devolución ni compensación previa (Art. 815 E.T.).",
  132: "Retenciones en la fuente a título de renta que le fueron practicadas durante el año gravable declarado (laborales, honorarios, servicios, compras, financieras).",
  133: "Anticipo de renta para el año gravable siguiente liquidado según el Art. 807 del Estatuto Tributario (procedimiento 1 o 2 con porcentajes del 25%, 50% o 75%).",
  134: "Saldo a pagar por impuesto: Casilla 129 - Casilla 130 - Casilla 131 - Casilla 132 + Casilla 133 (si el resultado es positivo).",
  135: "Sanciones: Sanción por extemporaneidad (Art. 641/642 E.T.), corrección (Art. 644 E.T.) u otras, sin que sea inferior a la sanción mínima de 10 UVT (Art. 639 E.T.).",
  136: "Total saldo a pagar: Casilla 129 - Casilla 130 - Casilla 131 - Casilla 132 + Casilla 133 + Casilla 135.",
  137: "Total saldo a favor: Casilla 130 + Casilla 131 + Casilla 132 - Casilla 129 - Casilla 133 - Casilla 135.",
  138: "Número de dependientes económicos (hasta 4) que otorgan el beneficio de 72 UVT cada uno según el Art. 336 inciso 2 del Estatuto Tributario.",
  139: "Adición por dependientes a la casilla 92: Valor en pesos resultante de multiplicar el número de dependientes de la casilla 138 (máximo 4) por 72 UVT del año gravable.",
  140: "¿Superó el límite del 60% de costos y gastos en rentas de trabajo de independientes? (Art. 336-1 E.T.). Marque X si los costos excedieron el 60% de los ingresos brutos.",
  141: "Aporte voluntario para financiar programas sociales y reducción de pobreza (Art. 244-1 E.T.).",
  980: "Pago total: Valor que se cancela en la entidad recaudadora con la presentación de esta declaración.",
  981: "Código de representación legal: Ingrese el código correspondiente si actúa en calidad de representante, apoderado, curador o albacea.",
  982: "Código de contador público o revisor fiscal.",
  983: "Número de tarjeta profesional del contador público que certifica la declaración.",
  994: "Con salvedades: Marque si la declaración se presenta con dictamen o certificación con salvedades por parte del contador.",
  996: "Espacio reservado para el adhesivo de la entidad recaudadora o radicación electrónica MUISCA.",
  997: "Espacio exclusivo para el sello y constancia de recepción de la entidad recaudadora autorizada.",
};
