/**
 * Diccionario Oficial del Instructivo DIAN para el Formulario 210
 * Declaración de Renta y Complementario de Personas Naturales y Asimiladas
 */

export interface FormulaExplicada {
  formula: string;
  descripcion: string;
  casillasInvolucradas: number[];
  ejemploCalculo?: (casillas: Record<number, number>) => string;
}

export const FORMULAS_EXPLICADAS_210: Record<number, FormulaExplicada> = {
  31: {
    formula: "Casilla 29 (Total Patrimonio Bruto) - Casilla 30 (Deudas)",
    descripcion: "Patrimonio líquido fiscal al 31 de diciembre. Es el valor real patrimonial neto una vez deducidas las obligaciones financieras y deudas soportadas.",
    casillasInvolucradas: [29, 30],
  },
  34: {
    formula: "Casilla 32 (Ingresos Brutos Trabajo) - Casilla 33 (INCRNGO)",
    descripcion: "Ingresos netos por rentas de trabajo (salarios, honorarios laborales, cesantías) después de restar los aportes obligatorios a salud, pensión y ARL (Ingresos No Constitutivos de Renta ni Ganancia Ocasional).",
    casillasInvolucradas: [32, 33],
  },
  37: {
    formula: "Casilla 35 (Aportes voluntarios FVP/AFC) + Casilla 36 (Otras rentas exentas / 25% laboral)",
    descripcion: "Total de rentas exentas originadas en rentas de trabajo (incluye la exención del 25% del numeral 10 del Art. 206 E.T. limitada a 790 UVT y cesantías).",
    casillasInvolucradas: [35, 36],
  },
  40: {
    formula: "Casilla 38 (Intereses de vivienda) + Casilla 39 (Otras deducciones / Medicina prepagada / GMF)",
    descripcion: "Total de deducciones imputables a la cédula de trabajo (intereses de crédito hipotecario hasta 1.200 UVT, medicina prepagada hasta 192 UVT y 50% del GMF).",
    casillasInvolucradas: [38, 39],
  },
  41: {
    formula: "Mínimo entre (Casilla 34 × 40%, Límite 1.340 UVT, Casilla 37 + Casilla 40)",
    descripcion: "Rentas exentas y deducciones limitadas de trabajo: Por disposición del Art. 336 del E.T., la suma de rentas exentas y deducciones no puede exceder el 40% del ingreso neto ni las 1.340 UVT anuales.",
    casillasInvolucradas: [34, 37, 40],
  },
  42: {
    formula: "Casilla 34 (Ingresos Netos) - Casilla 41 (Exentas y Deducciones Limitadas)",
    descripcion: "Renta líquida ordinaria de trabajo: Es el valor depurado que se integra a la cédula general.",
    casillasInvolucradas: [34, 41],
  },
  46: {
    formula: "Casilla 43 (Ingresos Brutos) - Casilla 44 (Devoluciones) - Casilla 45 (INCRNGO)",
    descripcion: "Ingresos netos por honorarios y compensación de servicios personales independientes no sujetos a costos.",
    casillasInvolucradas: [43, 44, 45],
  },
  49: {
    formula: "Casilla 47 (Aportes voluntarios FVP/AFC) + Casilla 48 (Otras rentas exentas)",
    descripcion: "Total de rentas exentas en rentas por honorarios y compensación de servicios personales.",
    casillasInvolucradas: [47, 48],
  },
  52: {
    formula: "Casilla 50 (Intereses de vivienda) + Casilla 51 (Otras deducciones imputables)",
    descripcion: "Total de deducciones imputables a la subcédula de honorarios y compensación de servicios.",
    casillasInvolucradas: [50, 51],
  },
  53: {
    formula: "Mínimo entre (Casilla 46 × 40%, Límite 1.340 UVT, Casilla 49 + Casilla 52)",
    descripcion: "Rentas exentas y deducciones limitadas de honorarios y servicios bajo el tope del 40% y 1.340 UVT.",
    casillasInvolucradas: [46, 49, 52],
  },
  57: {
    formula: "Casilla 46 (Ingresos Netos) - Casilla 53 (Exentas y Deducciones Limitadas) - Casilla 56 (Compensaciones)",
    descripcion: "Renta líquida ordinaria de la subcédula de honorarios y compensación de servicios personales.",
    casillasInvolucradas: [46, 53, 56],
  },
  61: {
    formula: "Casilla 58 (Ingresos Brutos) - Casilla 59 (Devoluciones) - Casilla 60 (INCRNGO)",
    descripcion: "Ingresos netos de capital (arrendamientos, intereses, rendimientos financieros y regalías) menos costos no constitutivos.",
    casillasInvolucradas: [58, 59, 60],
  },
  64: {
    formula: "Casilla 62 (Aportes voluntarios AFC/FVP) + Casilla 63 (Otras rentas exentas)",
    descripcion: "Total de rentas exentas imputables a rentas de capital.",
    casillasInvolucradas: [62, 63],
  },
  67: {
    formula: "Casilla 65 (Intereses de vivienda) + Casilla 66 (Otras deducciones imputables)",
    descripcion: "Total de deducciones imputables a rentas de capital.",
    casillasInvolucradas: [65, 66],
  },
  69: {
    formula: "Mínimo entre (Casilla 61 × 40%, Límite 1.340 UVT, Casilla 64 + Casilla 67)",
    descripcion: "Rentas exentas y deducciones limitadas en rentas de capital (límite legal del 40% y 1.340 UVT).",
    casillasInvolucradas: [61, 64, 67],
  },
  73: {
    formula: "Casilla 61 (Ingresos Netos) + Casilla 68 (Rentas ECE) - Casilla 69 (Exentas y Deducciones) - Casilla 72 (Pérdidas)",
    descripcion: "Renta líquida ordinaria final de la subcédula de rentas de capital.",
    casillasInvolucradas: [61, 68, 69, 72],
  },
  78: {
    formula: "Casilla 74 (Ingresos Brutos) - Casilla 75 (Devoluciones) - Casilla 76 (INCRNGO) - Casilla 77 (Costos y Deducciones)",
    descripcion: "Ingresos netos de rentas no laborales (comercio, agricultura, manufactura, servicios con costos procedentes).",
    casillasInvolucradas: [74, 75, 76, 77],
  },
  82: {
    formula: "Casilla 80 (Aportes AFC/FVP) + Casilla 81 (Otras rentas exentas no laborales)",
    descripcion: "Total rentas exentas imputables a rentas no laborales.",
    casillasInvolucradas: [80, 81],
  },
  85: {
    formula: "Casilla 83 (Intereses de vivienda) + Casilla 84 (Otras deducciones no laborales)",
    descripcion: "Total deducciones imputables a rentas no laborales.",
    casillasInvolucradas: [83, 84],
  },
  86: {
    formula: "Mínimo entre (Casilla 78 × 40%, Límite 1.340 UVT, Casilla 82 + Casilla 85)",
    descripcion: "Rentas exentas y deducciones limitadas de rentas no laborales (límite 40% y 1.340 UVT).",
    casillasInvolucradas: [78, 82, 85],
  },
  90: {
    formula: "Casilla 78 (Ingresos Netos) + Casilla 79 (Rentas ECE) - Casilla 86 (Exentas y Deducciones) - Casilla 89 (Pérdidas)",
    descripcion: "Renta líquida ordinaria final de rentas no laborales.",
    casillasInvolucradas: [78, 79, 86, 89],
  },
  91: {
    formula: "Casilla 34 (Trabajo) + Casilla 46 (Honorarios) + Casilla 61 (Capital) + Casilla 78 (No Laborales)",
    descripcion: "Renta líquida consolidada de la cédula general: Sumatoria de los ingresos netos de las 4 subcédulas (Art. 336 numeral 1 E.T.).",
    casillasInvolucradas: [34, 46, 61, 78],
  },
  92: {
    formula: "Casilla 41 (Trabajo) + Casilla 53 (Honorarios) + Casilla 69 (Capital) + Casilla 86 (No Laborales) + Casilla 139 (Dependientes 72 UVT) + Casilla 28 (1% Factura Electrónica)",
    descripcion: "Total de rentas exentas y deducciones imputables limitadas al 40% del ingreso neto (máx 1.340 UVT) más los beneficios adicionales sin límite (72 UVT por dependiente hasta 4 y 1% de compras soportadas con Factura Electrónica Art. 336 par. 5).",
    casillasInvolucradas: [41, 53, 69, 86, 139, 28],
  },
  93: {
    formula: "Casilla 42 (Trabajo) + Casilla 57 (Honorarios) + Casilla 73 (Capital) + Casilla 90 (No Laborales)",
    descripcion: "Renta líquida ordinaria de la cédula general: Sumatoria de los resultados netos ordinarios depurados de cada subcédula.",
    casillasInvolucradas: [42, 57, 73, 90],
  },
  97: {
    formula: "Casilla 93 (Renta Líquida Ordinaria) - Casilla 94 (Pérdidas 2018) - Casilla 95 (Exceso Presuntiva) + Casilla 96 (Rentas Gravables)",
    descripcion: "Renta líquida gravable de la cédula general: Es la base imponible definitiva sobre la que se calculará el impuesto de renta de la cédula general según la tabla progresiva del Art. 241 del Estatuto Tributario.",
    casillasInvolucradas: [93, 94, 95, 96],
  },
  101: {
    formula: "Casilla 99 (Ingresos Brutos Pensiones) - Casilla 100 (INCRNGO Salud/FSP)",
    descripcion: "Renta líquida de pensiones antes de exenciones.",
    casillasInvolucradas: [99, 100],
  },
  103: {
    formula: "Máximo entre (0, Casilla 101 - Casilla 102 Rentas Exentas Pensiones)",
    descripcion: "Renta líquida gravable de pensiones: Las mesadas pensionales que no excedan de 1.000 UVT mensuales están 100% exentas (Art. 206 numeral 5 E.T.). Solo el excedente tributa en la tabla del Art. 241.",
    casillasInvolucradas: [101, 102],
  },
  106: {
    formula: "Casilla 104 (Dividendos 2016) - Casilla 105 (INCRNGO)",
    descripcion: "Renta líquida ordinaria de dividendos correspondientes a utilidades generadas en 2016 y anteriores.",
    casillasInvolucradas: [104, 105],
  },
  111: {
    formula: "Mayor entre (Casilla 97, Casilla 98 Presuntiva) + Casilla 103 (Pensiones) + Casilla 107 (1ª Subcédula 2017+) + Casilla 109 (Dividendos Exterior) - Casilla 110 (Exentas CAN)",
    descripcion: "Renta líquida gravable combinada (Cédula General + Pensiones + Dividendos 1ª subcédula): Constituye la base consolidada para liquidar el impuesto en la tabla progresiva del Art. 241 del Estatuto Tributario.",
    casillasInvolucradas: [97, 98, 103, 107, 109, 110],
  },
  115: {
    formula: "Casilla 112 (Ingresos Ganancias Ocasionales) - Casilla 113 (Costos) - Casilla 114 (Exentas)",
    descripcion: "Ganancias ocasionales gravables: Base imponible sobre la cual se liquida la tarifa del 15% (o 20% para loterías, rifas y juegos de azar).",
    casillasInvolucradas: [112, 113, 114],
  },
  116: {
    formula: "Tabla Progresiva del Art. 241 del Estatuto Tributario sobre la Base de la Casilla 111",
    descripcion: "Impuesto determinado sobre rentas ordinarias: Aplica los 7 rangos de tarifas marginales en UVT (0%, 19%, 28%, 33%, 35%, 37% y 39%).",
    casillasInvolucradas: [111],
  },
  121: {
    formula: "Casilla 116 + Casilla 117 + Casilla 118 (Dividendos 35%) + Casilla 119 + Casilla 120",
    descripcion: "Total impuesto sobre las rentas líquidas gravables: Consolidado de impuesto de renta de todas las cédulas antes de descuentos.",
    casillasInvolucradas: [116, 117, 118, 119, 120],
  },
  125: {
    formula: "Casilla 122 (Impuestos Exterior) + Casilla 123 (Donaciones 25%) + Casilla 124 (Descuento Dividendos)",
    descripcion: "Total descuentos tributarios aplicables: Reducen directamente el impuesto a pagar sin generar saldo a favor (Art. 259 E.T.).",
    casillasInvolucradas: [122, 123, 124],
  },
  126: {
    formula: "Máximo entre (0, Casilla 121 - Casilla 125)",
    descripcion: "Impuesto neto de renta del año gravable.",
    casillasInvolucradas: [121, 125],
  },
  129: {
    formula: "Casilla 126 (Impuesto Neto) + Casilla 127 (Impuesto Ganancias Ocasionales) - Casilla 128 (Descuento Exterior GO)",
    descripcion: "Total impuesto a cargo del contribuyente por renta y ganancias ocasionales.",
    casillasInvolucradas: [126, 127, 128],
  },
  134: {
    formula: "Máximo entre (0, Casilla 129 - Casilla 130 - Casilla 131 - Casilla 132 + Casilla 133)",
    descripcion: "Saldo a pagar por impuesto antes de sanciones.",
    casillasInvolucradas: [129, 130, 131, 132, 133],
  },
  136: {
    formula: "Si (Casilla 129 + 133 + 135 > Casilla 130 + 131 + 132) => Casilla 129 + 133 + 135 - 130 - 131 - 132; Sino 0",
    descripcion: "Total saldo a pagar definitivo: Es el valor que debe consignarse en bancos a favor de la DIAN en la Casilla 980 (Pago Total).",
    casillasInvolucradas: [129, 133, 135, 130, 131, 132],
  },
  137: {
    formula: "Si (Casilla 130 + 131 + 132 > Casilla 129 + 133 + 135) => Casilla 130 + 131 + 132 - 129 - 133 - 135; Sino 0",
    descripcion: "Total saldo a favor del contribuyente: Puede solicitarse en devolución, compensación o arrastrarse a la declaración del año siguiente.",
    casillasInvolucradas: [130, 131, 132, 129, 133, 135],
  },
  980: {
    formula: "Igual a Casilla 136 (Total Saldo a Pagar)",
    descripcion: "Valor del pago total en bancos que acompaña la presentación de la declaración de renta.",
    casillasInvolucradas: [136],
  },
};

export const INSTRUCTIVO_DIAN_210: Record<number, string> = {
  1: "Año gravable correspondiente a la declaración tributaria. Para el periodo actual corresponde al AG 2024 / 2025.",
  4: "Número de formulario preimpreso asignado oficialmente por la DIAN o autogenerado por el sistema MUISCA.",
  5: "Número de Identificación Tributaria (NIT) o cédula de ciudadanía del declarante, tal como figura en la casilla 5 de la hoja principal del RUT, sin incluir el dígito de verificación.",
  6: "Dígito de verificación (DV) correspondiente al NIT o cédula del declarante (casilla 6 del RUT), calculado mediante el algoritmo oficial del módulo 11 del Estatuto Tributario.",
  7: "Primer apellido del declarante tal como figura en el RUT (casilla 31).",
  8: "Segundo apellido del declarante tal como figura en el RUT (casilla 32).",
  9: "Primer nombre del declarante tal como figura en el RUT (casilla 33).",
  10: "Otros nombres del declarante tal como figura en el RUT (casilla 34).",
  12: "Código de la Dirección Seccional de la DIAN con jurisdicción sobre el domicilio fiscal principal del declarante (casilla 12 del RUT).",
  24: "Código de la actividad económica principal del declarante según la clasificación CIIU Rev. 4 A.C. de la DIAN (casilla 46 del RUT).",
  25: "Código de corrección (1, 2, 3 o 4) según los Artículos 588 y 589 del Estatuto Tributario cuando se presenta una declaración en reemplazo de una anterior.",
  26: "Número de formulario anterior: Escriba el número de adhesivo o radicado de la declaración anterior que se corrige.",
  27: "Fracción de año gravable siguiente: Marque si declara por fracción de año con motivo de liquidación de sucesión ilíquida o cambio de domicilio fiscal.",
  28: "Deducción por compras soportadas con Factura Electrónica (Art. 336 parágrafo 5 E.T.): Corresponde al 1% del valor de las adquisiciones de bienes y servicios pagadas mediante medios electrónicos, sin que exceda de 240 UVT.",
  29: "Total patrimonio bruto: Incluye el valor patrimonial fiscal de todos los bienes y derechos apreciables en dinero poseídos en el país y en el exterior al 31 de diciembre (bienes raíces, vehículos, cuentas bancarias, acciones, inversiones, inventarios, etc.).",
  30: "Deudas: Incluye el saldo de las deudas y obligaciones financieras respaldadas con documento idóneo vigentes a 31 de diciembre.",
  31: "Total patrimonio líquido: Resultado de restar las deudas (casilla 30) del total patrimonio bruto (casilla 29).",
  32: "Ingresos brutos por rentas de trabajo: Salarios, comisiones, prestaciones sociales, viáticos, gastos de representación, honorarios de empleados y cesantías pagadas en el año.",
  33: "Ingresos no constitutivos de renta: Aportes obligatorios a salud (Art. 56 E.T.), pensión obligatoria (Art. 55 E.T.) y ARL.",
  34: "Renta líquida de trabajo: Casilla 32 - Casilla 33.",
  35: "Aportes voluntarios a fondos de pensiones voluntarias (FVP) y cuentas AFC/AVC (Art. 126-1 y 126-4 E.T., límite 30% del ingreso y máx 3.800 UVT).",
  36: "Otras rentas exentas de trabajo: Exención del 25% del numeral 10 del Art. 206 E.T. (hasta 790 UVT), cesantías e indemnizaciones exentas.",
  37: "Total rentas exentas de trabajo: Casilla 35 + Casilla 36.",
  38: "Intereses de crédito de vivienda para adquisición de casa de habitación (Art. 119 E.T., hasta 1.200 UVT).",
  39: "Otras deducciones de trabajo: Medicina prepagada y pólizas de salud (hasta 192 UVT), 50% del GMF (4x1000) e intereses ICETEX (hasta 100 UVT).",
  40: "Total deducciones de trabajo: Casilla 38 + Casilla 39.",
  41: "Rentas exentas y deducciones limitadas de trabajo: Suma de exentas y deducciones que no superan el 40% de la Casilla 34 ni las 1.340 UVT.",
  42: "Renta líquida ordinaria de trabajo: Casilla 34 - Casilla 41.",
  43: "Ingresos brutos por honorarios y compensación de servicios personales independientes no sujetos a costos.",
  44: "Devoluciones, rebajas y descuentos en honorarios y servicios.",
  45: "Ingresos no constitutivos de renta en honorarios (aportes obligatorios de salud y pensión como independiente).",
  46: "Ingresos netos por honorarios y servicios: Casilla 43 - Casilla 44 - Casilla 45.",
  47: "Aportes voluntarios AFC/FVP en honorarios.",
  48: "Otras rentas exentas en honorarios.",
  49: "Total rentas exentas en honorarios: Casilla 47 + Casilla 48.",
  50: "Intereses de vivienda en honorarios (hasta 1.200 UVT).",
  51: "Otras deducciones en honorarios (medicina prepagada, GMF 50%).",
  52: "Total deducciones en honorarios: Casilla 50 + Casilla 51.",
  53: "Rentas exentas y deducciones limitadas en honorarios (límite 40% / 1.340 UVT).",
  54: "Renta líquida ordinaria del ejercicio en honorarios: Casilla 46 - Casilla 53.",
  55: "Pérdida líquida del ejercicio en honorarios.",
  56: "Compensaciones por pérdidas fiscales en honorarios.",
  57: "Renta líquida ordinaria final en honorarios: Casilla 54 - Casilla 56.",
  58: "Ingresos brutos por rentas de capital: Intereses, rendimientos financieros, arrendamientos de bienes muebles/inmuebles y regalías.",
  59: "Devoluciones, rebajas y descuentos en rentas de capital.",
  60: "Ingresos no constitutivos de renta en capital: Componente inflacionario de rendimientos financieros y aportes a seguridad social.",
  61: "Ingresos netos por rentas de capital: Casilla 58 - Casilla 59 - Casilla 60.",
  62: "Aportes voluntarios AFC/FVP en rentas de capital (límite 30% / 3.800 UVT).",
  63: "Otras rentas exentas en rentas de capital.",
  64: "Total rentas exentas en rentas de capital: Casilla 62 + Casilla 63.",
  65: "Intereses de vivienda en rentas de capital (hasta 1.200 UVT).",
  66: "Otras deducciones en rentas de capital (GMF 50%, etc.).",
  67: "Total deducciones en rentas de capital: Casilla 65 + Casilla 66.",
  68: "Rentas líquidas pasivas de Entidades Controladas del Exterior (ECE) en rentas de capital.",
  69: "Rentas exentas y deducciones limitadas en rentas de capital (límite 40% / 1.340 UVT).",
  70: "Renta líquida ordinaria del ejercicio en rentas de capital: Casilla 61 + Casilla 68 - Casilla 69.",
  71: "Pérdida líquida del ejercicio en rentas de capital.",
  72: "Compensaciones por pérdidas fiscales en rentas de capital.",
  73: "Renta líquida ordinaria final en rentas de capital: Casilla 70 - Casilla 72.",
  74: "Ingresos brutos no laborales: Comercio, manufactura, servicios con costos procedentes y actividades agropecuarias.",
  75: "Devoluciones, rebajas y descuentos en rentas no laborales.",
  76: "Ingresos no constitutivos de renta en rentas no laborales.",
  77: "Costos y deducciones procedentes en rentas no laborales (cumpliendo requisitos del Art. 107 E.T.).",
  78: "Ingresos netos no laborales: Casilla 74 - Casilla 75 - Casilla 76 - Casilla 77.",
  79: "Rentas líquidas pasivas de Entidades Controladas del Exterior (ECE) en rentas no laborales.",
  80: "Aportes voluntarios AFC/FVP/AVC en rentas no laborales (máx 30% y 3.800 UVT).",
  81: "Otras rentas exentas no laborales (servicios hoteleros exentos consolidados, convenios CAN).",
  82: "Total rentas exentas no laborales: Casilla 80 + Casilla 81.",
  83: "Intereses de vivienda en rentas no laborales (hasta 1.200 UVT).",
  84: "Otras deducciones en rentas no laborales (GMF 50%, etc.).",
  85: "Total deducciones en rentas no laborales: Casilla 83 + Casilla 84.",
  86: "Rentas exentas y deducciones limitadas no laborales (límite 40% / 1.340 UVT).",
  87: "Renta líquida ordinaria del ejercicio no laboral: Casilla 78 + Casilla 79 - Casilla 86.",
  88: "Pérdida líquida del ejercicio no laboral.",
  89: "Compensaciones por pérdidas fiscales en rentas no laborales.",
  90: "Renta líquida ordinaria final no laboral: Casilla 87 - Casilla 89.",
  91: "Renta líquida total de la cédula general: Sumatoria de los ingresos netos de las 4 subcédulas (Casillas 34 + 46 + 61 + 78).",
  92: "Total rentas exentas y deducciones imputables limitadas: Suma de las casillas 41 + 53 + 69 + 86 + 139 (dependientes 72 UVT c/u) + 28 (1% factura electrónica).",
  93: "Renta líquida ordinaria cédula general: Sumatoria de Casillas 42 + 57 + 73 + 90.",
  94: "Compensaciones por pérdidas fiscales declaradas en años gravables 2018 y anteriores (Art. 330 parágrafo E.T.).",
  95: "Compensaciones por excesos de renta presuntiva sobre renta líquida ordinaria de años anteriores (Art. 189 E.T.).",
  96: "Rentas gravables: activos omitidos, pasivos inexistentes (Art. 239-1 E.T.) y renta líquida por comparación patrimonial no justificada.",
  97: "Renta líquida gravable cédula general: Resultado de Casilla 93 + Casilla 96 - Casilla 94 - Casilla 95. Constituye la base para aplicar la tarifa del Art. 241 E.T.",
  98: "Renta presuntiva del año gravable sobre patrimonio líquido del año anterior depurado (tarifa 0% vigente).",
  99: "Ingresos por pensiones de jubilación, invalidez, vejez, sobrevivientes, riesgos laborales y asignaciones de retiro de FFAA (país y exterior).",
  100: "Aportes obligatorios al sistema general de salud y Fondo de Solidaridad Pensional sobre mesadas pensionales.",
  101: "Renta líquida de pensiones: Casilla 99 - Casilla 100.",
  102: "Rentas exentas de pensiones: La parte de los pagos pensionales que no exceda de 1.000 UVT mensuales (Art. 206 num. 5 E.T.).",
  103: "Renta líquida gravable de pensiones: Casilla 101 - Casilla 102.",
  104: "Dividendos y participaciones pagados con utilidades generadas en periodos 2016 y anteriores.",
  105: "Ingresos no constitutivos de renta de dividendos 2016 y anteriores (distribuidos como no gravados según Art. 49 num. 3 E.T.).",
  106: "Renta líquida ordinaria de dividendos año 2016 y anteriores: Casilla 104 - Casilla 105.",
  107: "1ª Subcédula años 2017 y siguientes: Dividendos distribuidos como no gravados en cabeza de la sociedad (Art. 49 num. 3 E.T.), gravados con la tabla del Art. 242 inciso 1 E.T. (integrados en Casilla 111).",
  108: "2ª Subcédula años 2017 y siguientes: Dividendos procedentes de utilidades gravadas en la sociedad (Art. 49 par. 2 E.T.), gravados a la tarifa general del Art. 240 E.T. (35%).",
  109: "Dividendos y participaciones recibidos del exterior o de Entidades Controladas del Exterior (ECE).",
  110: "Rentas exentas sobre dividendos recibidos del exterior (convenios CAN Decisión 578).",
  111: "Base gravable para aplicar la tarifa del Art. 241 E.T.: Mayor valor entre Casilla 97 (Renta gravable) y Casilla 98 (Presuntiva) + Casilla 103 (Pensiones) + Casilla 107 + Casilla 109 - Casilla 110.",
  112: "Ingresos brutos por ganancias ocasionales: venta de activos fijos poseídos 2 años o más, herencias, legados, donaciones, porción conyugal, seguros de vida, loterías y rifas.",
  113: "Costo fiscal de los activos fijos enajenados que originaron la ganancia ocasional.",
  114: "Ganancias ocasionales no gravadas y exentas: primeras 13.000 UVT de vivienda del causante, 3.250 UVT de herencias, 5.000 UVT utilidad venta casa habitación (AFC) y seguros de vida (hasta 3.250 UVT).",
  115: "Ganancias ocasionales gravables: Casilla 112 - Casilla 113 - Casilla 114 (mínimo 0).",
  116: "Impuesto sobre las rentas líquidas gravables: Resultado de aplicar la tabla progresiva del Art. 241 E.T. a la base de la Casilla 111 cuando la renta ordinaria supera la presuntiva.",
  117: "Impuesto liquidado cuando la renta presuntiva es mayor que la renta ordinaria.",
  118: "Impuesto por dividendos 2ª subcédula 2017+ (Art. 240 E.T. al 35% sobre Casilla 108).",
  119: "Impuesto por dividendos gravados año 2016 y anteriores (según tarifas históricas Art. 241).",
  120: "Impuesto por dividendos y participaciones recibidas del exterior gravadas a la tarifa general.",
  121: "Total impuesto sobre las rentas líquidas gravables: Casilla 116 + Casilla 117 + Casilla 118 + Casilla 119 + Casilla 120.",
  122: "Descuento por impuestos pagados en el exterior sobre rentas de fuente extranjera (Art. 254 E.T.).",
  123: "Descuento tributario por donaciones a entidades del Régimen Tributario Especial (ESAL) y no contribuyentes (Art. 257 E.T., 25% del valor donado).",
  124: "Otros descuentos tributarios legalmente autorizados (Art. 254-1 E.T., etc.).",
  125: "Total descuentos tributarios: Casilla 122 + Casilla 123 + Casilla 124 (no pueden exceder el impuesto básico de renta según Art. 259 E.T.).",
  126: "Impuesto neto de renta: Casilla 121 - Casilla 125.",
  127: "Impuesto de ganancias ocasionales: 15% sobre la casilla 115 (o 20% para loterías, rifas y apuestas según Art. 317 E.T.).",
  128: "Descuento por impuestos pagados en el exterior imputables a ganancias ocasionales (Art. 254 E.T.).",
  129: "Total impuesto a cargo: Casilla 126 + Casilla 127 - Casilla 128.",
  130: "Anticipo de renta liquidado en el año gravable anterior para el presente periodo fiscal (Art. 807 E.T.).",
  131: "Saldo a favor del año gravable anterior sin solicitud de devolución ni compensación previa (Art. 815 E.T.).",
  132: "Retenciones en la fuente a título de renta que le fueron practicadas durante el año gravable declarado (laborales, honorarios, servicios, compras, financieras).",
  133: "Anticipo de renta para el año gravable siguiente liquidado según el Art. 807 del Estatuto Tributario (procedimiento 1 o 2 con porcentajes del 25%, 50% o 75%).",
  134: "Saldo a pagar por impuesto: Casilla 129 - Casilla 130 - Casilla 131 - Casilla 132 + Casilla 133 (si el resultado es positivo).",
  135: "Sanciones: Sanción por extemporaneidad (Art. 641/642 E.T.), corrección (Art. 644 E.T.) u otras, sin que sea inferior a la sanción mínima de 10 UVT (Art. 639 E.T.).",
  136: "Total saldo a pagar: Casilla 129 - Casilla 130 - Casilla 131 - Casilla 132 + Casilla 133 + Casilla 135.",
  137: "Total saldo a favor: Casilla 130 + Casilla 131 + Casilla 132 - Casilla 129 - Casilla 133 - Casilla 135.",
  138: "Número de dependientes económicos (hasta 4) que otorgan el beneficio de 72 UVT cada uno según el Art. 336 inciso 2 del Estatuto Tributario.",
  139: "Adición por dependientes a la casilla 92: Valor en pesos resultante de multiplicar el número de dependientes de la casilla 138 (máximo 4) por 72 UVT del año gravable.",
  140: "¿Superó el límite del 60% de costos y gastos en rentas de trabajo de independientes? (Art. 336-1 E.T.). Marque X si los costos excedieron el 60% de los ingresos brutos.",
  141: "Aporte voluntario para financiar programas sociales y reducción de pobreza (Art. 244-1 E.T.).",
  980: "Pago total: Valor que se cancela en la entidad recaudadora con la presentación de esta declaración.",
  981: "Código de representación legal: Ingrese el código correspondiente si actúa en calidad de representante, apoderado, curador o albacea.",
  982: "Código de contador público o revisor fiscal.",
  983: "Número de tarjeta profesional del contador público que certifica la declaración.",
  994: "Con salvedades: Marque si la declaración se presenta con dictamen o certificación con salvedades por parte del contador.",
  996: "Espacio reservado para el adhesivo de la entidad recaudadora o radicación electrónica MUISCA.",
  997: "Espacio exclusivo para el sello y constancia de recepción de la entidad recaudadora autorizada.",
};
