// ============================================================================
// INSTRUCTIVO OFICIAL DIAN - FORMULARIO 210 (AÑO GRAVABLE 2023, 2024, 2025 Y SIGUIENTES)
// Texto íntegro de orientación para el contribuyente según la DIAN MUISCA.
// ============================================================================

export interface CasillaInstructivo {
  num: number;
  label: string;
  legal: string;
  section: string;
  formula?: string;
  instructivo: string;
}

export const INSTRUCTIVO_DIAN_210: Record<number, string> = {
  1: "Corresponde al año gravable que está declarando.",
  4: "Espacio determinado para el número único asignado por la DIAN a cada uno de los formularios.",
  5: "Número de Identificación Tributaria asignado al contribuyente por la DIAN, sin el dígito de verificación, tal como aparece en la casilla 5 del RUT.",
  6: "Dígito de verificación (DV), tal como aparece en la casilla 6 de la hoja principal del RUT.",
  7: "Primer apellido que figura en la casilla 31 de la hoja principal del RUT.",
  8: "Segundo apellido que figura en la casilla 32 de la hoja principal del RUT.",
  9: "Primer nombre que figura en la casilla 33 de la hoja principal del RUT.",
  10: "Otros nombres que figuran en la casilla 34 de la hoja principal del RUT.",
  12: "Código de la dirección seccional que corresponda al domicilio principal de su actividad o negocio, según la casilla 12 del RUT.",
  24: "Código que corresponde a la actividad económica que le generó el mayor valor de ingresos en el período gravable a declarar (CIIU DIAN).",
  25: "Código de corrección: '1' si es corrección a declaración privada (Art. 588); '2' si disminuye impuesto (Art. 589); '3' provocada por acto administrativo.",
  26: "Número de formulario de la casilla 4 de la declaración objeto de corrección o del acto administrativo que se corrige.",
  27: "Seleccione SÍ si va a presentar declaración por la fracción del año gravable siguiente (liquidación de sucesión ilíquida o cancelación de RUT).",
  28: "Deducción del 1% del valor de las adquisiciones de bienes y/o servicios soportadas con factura electrónica de venta y pagadas por medios electrónicos, sin exceder 240 UVT en el año (Art. 336 num. 5 E.T.). No está sujeta al límite del 40%.",
  29: "Total del valor patrimonial de todos los bienes y derechos apreciables en dinero poseídos en el país o en el exterior a 31 de diciembre: efectivo, bancos, inversiones, inventarios, inmuebles, vehículos, etc. (Arts. 261 a 281 E.T.).",
  30: "Valor total de los saldos pendientes de pago a 31 de diciembre: obligaciones financieras, cuentas por pagar, pasivos por beneficios a empleados e impuestos por pagar (Arts. 283 a 287 E.T.).",
  31: "Total patrimonio líquido: Resultado de restar de la casilla 29 (Total patrimonio bruto) el valor de la casilla 30 (Deudas). Casilla 31 = Casilla 29 - Casilla 30.",
  32: "Salarios, primas, cesantías pagadas o retiradas, viáticos, gastos de representación, indemnizaciones, bonificaciones y demás conceptos laborales del país o exterior (Art. 103 E.T.).",
  33: "Aportes obligatorios a salud, pensión, Fondo de Solidaridad Pensional y apoyos económicos educativos condonados de origen laboral (Arts. 55 y 56 E.T.).",
  34: "Renta líquida de las rentas de trabajo: Casilla 32 (Ingresos brutos) menos Casilla 33 (Ingresos no constitutivos).",
  35: "Aportes voluntarios a fondos de pensiones voluntarias (FVP), cuentas AFC y cuentas AVC, hasta el 30% del ingreso laboral y máx 3.800 UVT anuales (Arts. 126-1 y 126-4 E.T.).",
  36: "Otras rentas exentas laborales: incluye el 25% exento laboral (Art. 206 num. 10 E.T., límite 790 UVT), indemnizaciones por accidente/enfermedad, gastos de entierro y convenios CAN.",
  37: "Total rentas exentas de trabajo: Suma de la casilla 35 y la casilla 36.",
  38: "Intereses y/o corrección monetaria pagados sobre préstamos para adquisición de vivienda de habitación del contribuyente, limitado a 1.200 UVT en el año (Art. 119 E.T.).",
  39: "Otras deducciones: dependientes económicos (10% mensual hasta 32 UVT/mes), medicina prepagada (hasta 16 UVT/mes), 50% del GMF e intereses ICETEX (hasta 100 UVT).",
  40: "Total deducciones imputables de trabajo: Suma de la casilla 38 y la casilla 39.",
  41: "Rentas exentas y deducciones imputables limitadas de trabajo: Porción imputable que, junto con las demás cédulas, no supera el 40% del ingreso neto ni 1.340 UVT anuales.",
  42: "Renta líquida ordinaria de las rentas de trabajo: Resultado positivo de restar de la casilla 34 el valor de la casilla 41.",
  43: "Ingresos por honorarios, comisiones y servicios personales percibidos como independiente que opta por deducir costos y gastos procedentes en lugar del 25% exento laboral.",
  44: "Ingresos no constitutivos de renta aplicables a honorarios con costos (aportes a salud y pensión obligatorios).",
  45: "Costos y gastos procedentes directamente asociados a la actividad que cumplan los requisitos del Art. 107 y Art. 771-2 del E.T.",
  46: "Renta líquida de honorarios con costos: Casilla 43 - Casilla 44 - Casilla 45.",
  47: "Aportes voluntarios AFC, FVP y AVC imputables a honorarios (máx 30% ingreso y 3.800 UVT).",
  48: "Otras rentas exentas aplicables a honorarios (convenios CAN, etc.).",
  49: "Total rentas exentas de honorarios: Casilla 47 + Casilla 48.",
  50: "Intereses de vivienda imputables a honorarios (hasta 1.200 UVT).",
  51: "Otras deducciones imputables a honorarios (GMF 50%, salud prepagada, dependientes si no se tomaron en trabajo).",
  52: "Total deducciones imputables de honorarios: Casilla 50 + Casilla 51.",
  53: "Rentas exentas y deducciones imputables limitadas de honorarios dentro del límite global del 40% (1.340 UVT).",
  54: "Renta líquida ordinaria del ejercicio: Casilla 46 - Casilla 53.",
  55: "Pérdida líquida ordinaria del ejercicio de honorarios cuando los costos superan los ingresos netos.",
  56: "Compensaciones por pérdidas fiscales de años anteriores acumuladas en honorarios.",
  57: "Renta líquida ordinaria final de honorarios: Casilla 54 - Casilla 56.",
  58: "Rendimientos financieros, intereses, arrendamientos de bienes muebles/inmuebles, regalías y propiedad intelectual (país y exterior).",
  59: "Componente inflacionario no gravado y aportes a seguridad social imputables a rentas de capital.",
  60: "Costos y gastos procedentes asociados a la generación de rentas de capital (mantenimiento, administración, predial, etc. Art. 107 E.T.).",
  61: "Renta líquida de capital: Casilla 58 - Casilla 59 - Casilla 60.",
  62: "Rentas líquidas pasivas provenientes de Entidades Controladas del Exterior (ECE) en rentas de capital (Art. 884 E.T.).",
  63: "Aportes voluntarios AFC/FVP/AVC aplicables a rentas de capital (máx 30% ingreso y 3.800 UVT).",
  64: "Otras rentas exentas de capital (convenios CAN).",
  65: "Total rentas exentas de capital: Casilla 63 + Casilla 64.",
  66: "Intereses de vivienda aplicables a capital (hasta 1.200 UVT).",
  67: "Otras deducciones de capital (GMF 50%, intereses ICETEX).",
  68: "Total deducciones de capital: Casilla 66 + Casilla 67.",
  69: "Rentas exentas y deducciones limitadas de capital (dentro del límite del 40% / 1.340 UVT).",
  70: "Renta líquida ordinaria del ejercicio de capital: Casilla 61 + Casilla 62 - Casilla 69.",
  71: "Pérdida líquida del ejercicio en rentas de capital.",
  72: "Compensaciones por pérdidas fiscales acumuladas en rentas de capital.",
  73: "Renta líquida ordinaria final de capital: Casilla 70 - Casilla 72.",
  74: "Ingresos por actividades comerciales, industriales, agrícolas, servicios no personales y enajenación de activos poseídos por menos de 2 años.",
  75: "Devoluciones, rebajas y descuentos en ventas de rentas no laborales.",
  76: "Ingresos no constitutivos de renta de rentas no laborales (aportes seguridad social, apoyos educativos públicos, utilidades en bolsa < 3%).",
  77: "Costos de ventas de mercancías, materias primas, mano de obra y gastos deducibles de administración y ventas (Art. 107 E.T.).",
  78: "Renta líquida no laboral: Casilla 74 - Casilla 75 - Casilla 76 - Casilla 77.",
  79: "Rentas líquidas pasivas de Entidades Controladas del Exterior (ECE) en rentas no laborales.",
  80: "Aportes voluntarios AFC/FVP/AVC en rentas no laborales (máx 30% y 3.800 UVT).",
  81: "Otras rentas exentas no laborales (servicios hoteleros exentos consolidados, convenios CAN).",
  82: "Total rentas exentas no laborales: Casilla 80 + Casilla 81.",
  83: "Intereses de vivienda en rentas no laborales (hasta 1.200 UVT).",
  84: "Otras deducciones en rentas no laborales (GMF 50%, etc.).",
  85: "Total deducciones en rentas no laborales: Casilla 83 + Casilla 84.",
  86: "Rentas exentas y deducciones limitadas no laborales (límite 40% / 1.340 UVT).",
  87: "Renta líquida ordinaria del ejercicio no laboral: Casilla 78 + Casilla 79 - Casilla 86.",
  88: "Pérdida líquida del ejercicio no laboral.",
  89: "Compensaciones por pérdidas fiscales en rentas no laborales.",
  90: "Renta líquida ordinaria final no laboral: Casilla 87 - Casilla 89.",
  91: "Renta líquida total de la cédula general: Sumatoria de las rentas de trabajo, honorarios, capital y no laborales (Casillas 41 + 42 + 53 + 57 + 69 + 73 + 86 + 90).",
  92: "Total rentas exentas y deducciones imputables limitadas: Suma de las casillas 28 + 41 + 53 + 69 + 86 + 139 (límite 40% o 1.340 UVT, más 72 UVT por dependiente y 1% factura electrónica).",
  93: "Renta líquida ordinaria cédula general: Casilla 91 - Casilla 92.",
  94: "Compensaciones por pérdidas fiscales declaradas en años gravables 2018 y anteriores (Art. 330 parágrafo E.T.).",
  95: "Compensaciones por excesos de renta presuntiva sobre renta líquida ordinaria de años anteriores (Art. 189 E.T.).",
  96: "Rentas gravables: activos omitidos, pasivos inexistentes (Art. 239-1 E.T.) y renta líquida por comparación patrimonial no justificada.",
  97: "Renta líquida gravable cédula general: Resultado de Casilla 93 + Casilla 96 - Casilla 94 - Casilla 95.",
  98: "Renta presuntiva del año gravable sobre patrimonio líquido del año anterior depurado (tarifa 0% vigente).",
  99: "Ingresos por pensiones de jubilación, invalidez, vejez, sobrevivientes, riesgos laborales y asignaciones de retiro de FFAA (país y exterior).",
  100: "Aportes obligatorios al sistema general de salud y Fondo de Solidaridad Pensional sobre mesadas pensionales.",
  101: "Renta líquida de pensiones: Casilla 99 - Casilla 100.",
  102: "Rentas exentas de pensiones: La parte de los pagos pensionales que no exceda de 1.000 UVT mensuales (Art. 206 num. 5 E.T.).",
  103: "Renta líquida gravable de pensiones: Casilla 101 - Casilla 102.",
  104: "Dividendos y participaciones pagados con utilidades generadas en periodos 2016 y anteriores.",
  105: "Ingresos no constitutivos de renta de dividendos 2016 y anteriores (distribuidos como no gravados según Art. 49 num. 3 E.T.).",
  106: "Renta líquida ordinaria de dividendos año 2016 y anteriores: Casilla 104 - Casilla 105.",
  107: "1ª Subcédula años 2017 y siguientes: Dividendos distribuidos como no gravados en cabeza de la sociedad (Art. 49 num. 3 E.T.), gravados con la tabla del Art. 242 inciso 1 E.T. (integrados en Casilla 111).",
  108: "2ª Subcédula años 2017 y siguientes: Dividendos procedentes de utilidades gravadas en la sociedad (Art. 49 par. 2 E.T.), gravados a la tarifa general del Art. 240 E.T. (35%).",
  109: "Dividendos y participaciones recibidos del exterior o de Entidades Controladas del Exterior (ECE).",
  110: "Rentas exentas sobre dividendos recibidos del exterior (convenios CAN Decisión 578).",
  111: "Base gravable para aplicar la tarifa del Art. 241 E.T.: Mayor valor entre Casilla 97 (Renta gravable) y Casilla 98 (Presuntiva) + Casilla 103 (Pensiones) + Casilla 107 + Casilla 108 - Casilla 118.",
  112: "Ingresos brutos por ganancias ocasionales: venta de activos fijos poseídos 2 años o más, herencias, legados, donaciones, porción conyugal, seguros de vida, loterías y rifas.",
  113: "Costo fiscal de los activos fijos enajenados que originaron la ganancia ocasional.",
  114: "Ganancias ocasionales no gravadas y exentas: primeras 13.000 UVT de vivienda del causante, 3.250 UVT de herencias, 5.000 UVT utilidad venta casa habitación (AFC) y seguros de vida (hasta 3.250 UVT).",
  115: "Ganancias ocasionales gravables: Casilla 112 - Casilla 113 - Casilla 114 (mínimo 0).",
  116: "Impuesto sobre las rentas líquidas gravables: Resultado de aplicar la tabla progresiva del Art. 241 E.T. a la base de la Casilla 111 cuando la renta ordinaria supera la presuntiva.",
  117: "Impuesto liquidado cuando la renta presuntiva es mayor que la renta ordinaria.",
  118: "Impuesto por dividendos 2ª subcédula 2017+ (Art. 240 E.T. al 35% sobre Casilla 108).",
  119: "Impuesto por dividendos gravados año 2016 y anteriores (según tarifas históricas Art. 241).",
  120: "Impuesto por dividendos recibidos del exterior: 35% sobre Casilla 109 menos Casilla 110.",
  121: "Total impuesto sobre las rentas líquidas gravables: Suma de Casillas 116 + 117 + 118 + 119 + 120.",
  122: "Descuento por impuestos pagados en el exterior sobre rentas de fuente extranjera (Art. 254 E.T. y convenios de doble imposición).",
  123: "Descuento tributario por donaciones a entidades sin ánimo de lucro (ESAL régimen especial, 25% del valor donado Art. 257 E.T.) e inversiones en ciencia y tecnología (30% Art. 256 E.T.).",
  124: "Descuento por dividendos recibidos de la 1ª subcédula (Art. 254-1 E.T.) y otros descuentos de ley.",
  125: "Total descuentos tributarios: Suma de Casillas 122 + 123 + 124 (con límite general del 30% del impuesto a cargo según Art. 259 E.T.).",
  126: "Impuesto neto de renta: Casilla 121 - Casilla 125.",
  127: "Impuesto de ganancias ocasionales: 20% para loterías, rifas y apuestas; 15% para las demás ganancias ocasionales gravables (Casilla 115).",
  128: "Descuento por impuestos pagados en el exterior aplicable a ganancias ocasionales.",
  129: "Total impuesto a cargo: Casilla 126 (Impuesto neto) + Casilla 127 (Ganancias ocasionales) - Casilla 128 (Descuento exterior).",
  130: "Anticipo de renta liquidado en la declaración del año gravable anterior para el presente año.",
  131: "Saldo a favor del año gravable anterior sin solicitud de devolución y/o compensación.",
  132: "Retenciones y autorretenciones en la fuente a título de renta y ganancias ocasionales practicadas en el año.",
  133: "Anticipo de renta para el año gravable siguiente: 25% (1.er año), 50% (2.º año) o 75% (3.er año en adelante) menos retenciones de la Casilla 132.",
  134: "Saldo a pagar por impuesto: Casilla 129 + Casilla 133 - Casilla 130 - Casilla 131 - Casilla 132 (cuando el resultado es positivo).",
  135: "Sanciones por extemporaneidad o corrección (no inferior a la sanción mínima de 10 UVT del año de presentación según Art. 639 E.T.).",
  136: "Total saldo a pagar: Casilla 129 + Casilla 133 + Casilla 135 - Casilla 130 - Casilla 131 - Casilla 132.",
  137: "Total saldo a favor: Casilla 130 + Casilla 131 + Casilla 132 - Casilla 129 - Casilla 133 - Casilla 135.",
  138: "Número de dependientes económicos registrados (hasta 4 dependientes).",
  139: "Adición por dependientes a la casilla 92: 72 UVT por cada dependiente económico (hasta un máximo de 4 dependientes = 288 UVT en adición al 40%).",
  140: "Marca 'X' obligatoria si el porcentaje de costos y gastos deducibles en honorarios (Casilla 45 / Casilla 43) supera el 60% indicativo (Art. 336-1 E.T.).",
  141: "Aporte voluntario para programas sociales contra la pobreza extrema y discapacidad (Art. 244-1 E.T.).",
  980: "Pago total realizado al momento de la declaración (por defecto 0 en formulario virtual; se paga con formulario 490).",
  981: "Código de representación de quien firma por el declarante (según casilla 98 del RUT).",
  982: "Código 1 de Contador o Revisor Fiscal (obligatorio si ingresos o patrimonio bruto superan 100.000 UVT o si está obligado a llevar contabilidad).",
  994: "Marca 'X' si el contador firma la declaración con salvedades.",
  996: "Espacio para número interno o autoadhesivo de la DIAN / entidad recaudadora.",
  997: "Espacio para el sello y fecha de la entidad recaudadora.",
};
