import { ET_EXTRA } from "./et-extra";

export type LegalSource = "ET" | "DUR" | "CP" | "CCO" | "LEY" | "RES" | "CAN" | "DIAN";

export type LegalArticle = {
  id: string;
  source: LegalSource;
  citation: string;
  title: string;
  summary: string;
  text: string;
  tags: string[];
  url: string;
  casillas?: number[];
};

export const SOURCE_META: Record<
  LegalSource,
  { label: string; official: string }
> = {
  ET: {
    label: "Estatuto Tributario",
    official: "http://www.secretariasenado.gov.co/senado/basedoc/estatuto_tributario.html"
  },
  DUR: {
    label: "Decreto 1625 de 2016 (DUR Tributario)",
    official: "https://www.funcionpublica.gov.co/eva/gestornormativo/norma.php?i=77801"
  },
  CP: {
    label: "Constitución Política de 1991",
    official: "http://www.secretariasenado.gov.co/senado/basedoc/constitucion_politica_1991.html"
  },
  CCO: {
    label: "Código de Comercio",
    official: "http://www.secretariasenado.gov.co/senado/basedoc/codigo_comercio.html"
  },
  LEY: {
    label: "Leyes y decretos",
    official: "http://www.secretariasenado.gov.co/senado/basedoc/ley_2277_2022.html"
  },
  RES: {
    label: "Resoluciones DIAN",
    official: "https://www.dian.gov.co/normatividad/Paginas/default.aspx"
  },
  CAN: {
    label: "Comunidad Andina",
    official: "https://www.comunidadandina.org/normativa-andina/decisiones/"
  },
  DIAN: {
    label: "DIAN — instructivos y calendarios",
    official: "https://www.dian.gov.co"
  }
};

export const ARTICLES: LegalArticle[] = [
  {
    id: "cp-95",
    source: "CP",
    citation: "Art. 95 C.P.",
    title: "Deberes de la persona y del ciudadano",
    summary: "Incluye el deber de contribuir al financiamiento de los gastos e inversiones del Estado dentro de conceptos de justicia y equidad.",
    text: "Son deberes de la persona y del ciudadano: … 9. Contribuir al financiamiento de los gastos e inversiones del Estado dentro de conceptos de justicia y equidad.",
    tags: ["constitucion","deberes"],
    url: "http://www.secretariasenado.gov.co/senado/basedoc/constitucion_politica_1991.html#95",
  },
  {
    id: "cp-338",
    source: "CP",
    citation: "Art. 338 C.P.",
    title: "Legalidad tributaria",
    summary: "Solo la ley, las ordenanzas y los acuerdos pueden imponer tributos. La ley fija los sujetos, hechos, bases, tarifas y sujetos pasivos.",
    text: "En tiempo de paz, solamente el Congreso, las asambleas departamentales y los concejos distritales y municipales podrán imponer contribuciones fiscales o parafiscales. La ley, las ordenanzas y los acuerdos deben fijar, directamente, los sujetos activos y pasivos, los hechos y las bases gravables, y las tarifas de los impuestos.",
    tags: ["legalidad","tarifas"],
    url: "http://www.secretariasenado.gov.co/senado/basedoc/constitucion_politica_1991.html#338",
  },
  {
    id: "cp-363",
    source: "CP",
    citation: "Art. 363 C.P.",
    title: "Principios del sistema tributario",
    summary: "El sistema tributario se funda en los principios de equidad, eficiencia y progresividad.",
    text: "El sistema tributario se funda en los principios de equidad, eficiencia y progresividad. Las leyes tributarias no se aplicarán con retroactividad.",
    tags: ["principios","progresividad"],
    url: "http://www.secretariasenado.gov.co/senado/basedoc/constitucion_politica_1991.html#363",
  },
  {
    id: "et-9",
    source: "ET",
    citation: "Art. 9 E.T.",
    title: "Imputación de rentas de fuente nacional y extranjera",
    summary: "Las personas naturales residentes están sujetas al impuesto sobre su renta y ganancias ocasionales, de fuente nacional y extranjera.",
    text: "Las personas naturales, nacionales o extranjeras, residentes en el país y las sucesiones ilíquidas de causantes con residencia en el país en el momento de su muerte, están sujetas al impuesto sobre la renta y complementarios en lo concerniente a sus rentas y ganancias ocasionales, tanto de fuente nacional como de fuente extranjera, y a su patrimonio poseído dentro y fuera del país.",
    tags: ["residencia","sujeto"],
    url: "http://www.secretariasenado.gov.co/senado/basedoc/estatuto_tributario.html#9",
    casillas: [32,58,74,99,112],
  },
  {
    id: "et-10",
    source: "ET",
    citation: "Art. 10 E.T.",
    title: "Residencia fiscal",
    summary: "Es residente quien permanece más de 183 días (continuos o discontinuos) durante un período cualquiera de 365 días, o quien cumple los demás criterios de familia, nacionalidad y núcleo esencial.",
    text: "Se consideran residentes en Colombia para efectos tributarios las personas naturales que cumplan con cualquiera de las siguientes condiciones: 1. Permanecer continua o discontinuamente en el país por más de ciento ochenta y tres (183) días calendario, incluyendo días de entrada y salida del país, durante un periodo cualquiera de trescientos sesenta y cinco (365) días calendario consecutivos. … También hay residencia por familia, nacionalidad colombiana con criterio de núcleo esencial de negocios o de ingresos/patrimonio en Colombia, entre otros supuestos del artículo.",
    tags: ["residencia","183 dias"],
    url: "http://www.secretariasenado.gov.co/senado/basedoc/estatuto_tributario.html#10",
  },
  {
    id: "et-26",
    source: "ET",
    citation: "Art. 26 E.T.",
    title: "Los ingresos son rentas ordinarias salvo disposición en contrario",
    summary: "Base de la renta líquida: ingresos ordinarios y extraordinarios realizados en el año, menos costos y deducciones.",
    text: "La renta líquida gravable se determina restando de la suma de todos los ingresos ordinarios y extraordinarios realizados en el año o período gravable, que sean susceptibles de producir un incremento neto del patrimonio en el momento de su percepción, y que no hayan sido expresamente exceptuados, los costos y las deducciones autorizados por la ley.",
    tags: ["renta liquida","ingresos"],
    url: "http://www.secretariasenado.gov.co/senado/basedoc/estatuto_tributario.html#26",
  },
  {
    id: "et-27",
    source: "ET",
    citation: "Art. 27 E.T.",
    title: "Realización del ingreso para no obligados a llevar contabilidad",
    summary: "Los ingresos se entienden realizados cuando se reciben efectivamente en dinero o en especie. Inmuebles: en la fecha de la escritura.",
    text: "Se entiende realizado el ingreso para los no obligados a llevar libros de contabilidad cuando se recibe efectivamente en dinero o en especie, o cuando el derecho se causa, en los casos de enajenación de bienes inmuebles, en la fecha de la escritura pública correspondiente (numeral 2).",
    tags: ["realizacion","escritura"],
    url: "http://www.secretariasenado.gov.co/senado/basedoc/estatuto_tributario.html#27",
    casillas: [112,74],
  },
  {
    id: "et-29-1",
    source: "ET",
    citation: "Art. 29-1 E.T.",
    title: "Ingresos en especie",
    summary: "La remuneración en especie se valora y forma parte de la renta de trabajo.",
    text: "Los ingresos en especie se encuentran gravados en cabeza del beneficiario, en el valor comercial del bien o servicio. Tratándose de salarios, el empleador debe reportarlos en el certificado de ingresos y retenciones.",
    tags: ["especie","trabajo"],
    url: "http://www.secretariasenado.gov.co/senado/basedoc/estatuto_tributario.html#29-1",
    casillas: [32],
  },
  {
    id: "et-35",
    source: "ET",
    citation: "Art. 35 E.T.",
    title: "Intereses presuntivos",
    summary: "Los préstamos a socios o vinculados generan un interés mínimo presunto.",
    text: "Para efectos del impuesto sobre la renta, se presume de derecho que todo préstamo en dinero, cualquiera que sea su naturaleza o denominación, que otorguen las sociedades a sus socios o accionistas, o estos a aquellas, genera un rendimiento mínimo anual y proporcional al tiempo de posesión, equivalente a la tasa de interés más representativa del mercado determinada por la autoridad competente.",
    tags: ["intereses","capital"],
    url: "http://www.secretariasenado.gov.co/senado/basedoc/estatuto_tributario.html#35",
    casillas: [58],
  },
  {
    id: "et-38",
    source: "ET",
    citation: "Arts. 38 a 41 E.T.",
    title: "Componente inflacionario",
    summary: "Parte no constitutiva de renta de los rendimientos financieros de personas naturales no obligadas a llevar contabilidad.",
    text: "No constituye renta ni ganancia ocasional el componente inflacionario de los rendimientos financieros percibidos por personas naturales y sucesiones ilíquidas, no obligadas a llevar libros de contabilidad, de conformidad con los artículos 38 y 41 del E.T. Igual tratamiento tiene el componente inflacionario que distribuyan fondos de inversión, mutuos y de valores (art. 39).",
    tags: ["incrngo","capital"],
    url: "http://www.secretariasenado.gov.co/senado/basedoc/estatuto_tributario.html#38",
    casillas: [59],
  },
  {
    id: "et-45",
    source: "ET",
    citation: "Art. 45 E.T.",
    title: "Indemnizaciones por seguro de daño",
    summary: "No constituyen renta las indemnizaciones de seguros de daño en la parte que corresponda a daño emergente.",
    text: "No constituyen renta ni ganancia ocasional las indemnizaciones de seguros por daño emergente. La parte que corresponda a lucro cesante sí es gravada. En la determinación cedular de personas naturales, la DIAN las ubica como ingreso no constitutivo de renta en la cédula de rentas no laborales.",
    tags: ["incrngo","seguros","no laborales"],
    url: "http://www.secretariasenado.gov.co/senado/basedoc/estatuto_tributario.html#45",
    casillas: [76],
  },
  {
    id: "et-46",
    source: "ET",
    citation: "Art. 46 E.T.",
    title: "Apoyos económicos para programas educativos",
    summary: "Los apoyos económicos para financiar programas educativos son INCRNGO, imputables a trabajo y a no laborales.",
    text: "No constituyen renta ni ganancia ocasional los apoyos económicos no reembolsables o condonados, otorgados por el Estado o por instituciones de educación superior, para financiar programas educativos. En la matriz cedular DIAN (Renta 2025) se imputan a rentas de trabajo y a rentas no laborales, no a honorarios con costos ni a capital.",
    tags: ["incrngo","educacion","trabajo"],
    url: "http://www.secretariasenado.gov.co/senado/basedoc/estatuto_tributario.html#46",
    casillas: [33,76],
  },
  {
    id: "et-48",
    source: "ET",
    citation: "Arts. 48 y 49 E.T.",
    title: "Dividendos no constitutivos de renta",
    summary: "Define qué porción de las utilidades se puede distribuir como INCRNGO (num. 3) y cuál está gravada (parágrafo 2).",
    text: "Los dividendos y participaciones percibidos de sociedades nacionales y extranjeras son gravados o no según el procedimiento de los artículos 48 y 49. El numeral 3 del art. 49 identifica las utilidades que pueden distribuirse como ingreso no constitutivo de renta. El parágrafo 2 identifica las utilidades gravadas. El año de origen (2016 y anteriores vs. 2017 y siguientes) cambia la tarifa (arts. 242 y 241).",
    tags: ["dividendos","art49"],
    url: "http://www.secretariasenado.gov.co/senado/basedoc/estatuto_tributario.html#48",
    casillas: [104,105,107,108],
  },
  {
    id: "et-55",
    source: "ET",
    citation: "Art. 55 E.T.",
    title: "Aportes a fondos de pensiones",
    summary: "Cotizaciones obligatorias y, con límite, las voluntarias al RAIS son INCRNGO.",
    text: "Las cotizaciones obligatorias al Sistema General de Pensiones son ingreso no constitutivo de renta ni ganancia ocasional. Las cotizaciones voluntarias al RAIS, desde 2019, lo son hasta el 25 % del ingreso laboral o tributario anual, limitado a 2.500 UVT. Los retiros para fines distintos a pensión o retiro anticipado se gravan en el año del retiro.",
    tags: ["pension","incrngo","rais"],
    url: "http://www.secretariasenado.gov.co/senado/basedoc/estatuto_tributario.html#55",
    casillas: [33],
  },
  {
    id: "et-56",
    source: "ET",
    citation: "Art. 56 E.T.",
    title: "Aportes obligatorios a salud",
    summary: "Los aportes obligatorios al sistema general de seguridad social en salud son INCRNGO en todas las cédulas de la general.",
    text: "Los aportes obligatorios al Sistema General de Seguridad Social en Salud no constituyen renta ni ganancia ocasional. A diferencia de las cotizaciones voluntarias, no tienen tope de 2.500 UVT. La matriz cedular DIAN los admite en trabajo, honorarios, capital y no laborales.",
    tags: ["salud","incrngo"],
    url: "http://www.secretariasenado.gov.co/senado/basedoc/estatuto_tributario.html#56",
    casillas: [33,44,59,76],
  },
  {
    id: "et-103",
    source: "ET",
    citation: "Art. 103 E.T.",
    title: "Qué son rentas de trabajo",
    summary: "Salarios, comisiones, prestaciones, honorarios y compensaciones por servicios personales.",
    text: "Se consideran rentas de trabajo las obtenidas por personas naturales por concepto de salarios, comisiones, prestaciones sociales, viáticos, gastos de representación, honorarios, emolumentos eclesiásticos, compensaciones por servicios personales y, en general, toda clase de remuneraciones originadas en una relación laboral, legal o reglamentaria, o de una relación de prestación de servicios personales.",
    tags: ["trabajo","honorarios"],
    url: "http://www.secretariasenado.gov.co/senado/basedoc/estatuto_tributario.html#103",
    casillas: [32,43],
  },
  {
    id: "et-107",
    source: "ET",
    citation: "Arts. 107 y 107-1 E.T.",
    title: "Causalidad, necesidad y proporcionalidad",
    summary: "Las deducciones deben ser necesarias, proporcionales y con relación de causalidad con la actividad productora de renta.",
    text: "Son deducibles las expensas realizadas durante el año gravable en el desarrollo de cualquier actividad productora de renta, siempre que tengan relación de causalidad con las actividades productoras de renta y que sean necesarias y proporcionadas de acuerdo con cada actividad. El art. 107-1 limita ciertas deducciones.",
    tags: ["deducciones","costos"],
    url: "http://www.secretariasenado.gov.co/senado/basedoc/estatuto_tributario.html#107",
    casillas: [45,60,77],
  },
  {
    id: "et-115",
    source: "ET",
    citation: "Art. 115 E.T.",
    title: "Deducción de impuestos pagados y del GMF",
    summary: "El 50 % del GMF es deducible. Desde AG 2023, el 100 % de impuestos, tasas y contribuciones pagados con causalidad (excepto renta).",
    text: "El cincuenta por ciento (50 %) del Gravamen a los Movimientos Financieros será deducible, independientemente de su relación de causalidad, siempre que esté certificado por el agente retenedor. Para el año gravable 2023 y siguientes es deducible el 100 % de los impuestos, tasas y contribuciones efectivamente pagados que tengan relación de causalidad con la actividad económica, con excepción del impuesto sobre la renta.",
    tags: ["gmf","ica","deducciones"],
    url: "http://www.secretariasenado.gov.co/senado/basedoc/estatuto_tributario.html#115",
    casillas: [39],
  },
  {
    id: "et-117",
    source: "ET",
    citation: "Art. 117 E.T.",
    title: "Deducción de intereses",
    summary: "Los intereses a terceros son deducibles hasta la tasa más alta autorizada a los bancos, certificada por la Superintendencia Financiera.",
    text: "El gasto por intereses devengado a favor de terceros será deducible en la parte que no exceda la tasa más alta que se haya autorizado cobrar a los establecimientos bancarios durante el respectivo año, certificada por la Superintendencia Financiera. El exceso no es deducible. Concuerda con el art. 118-1 (subcapitalización) cuando el acreedor es vinculado.",
    tags: ["intereses","deducciones","117"],
    url: "http://www.secretariasenado.gov.co/senado/basedoc/estatuto_tributario.html#117",
    casillas: [45,60,77],
  },
  {
    id: "et-118",
    source: "ET",
    citation: "Art. 118 E.T.",
    title: "El componente inflacionario no es deducible",
    summary: "La parte inflacionaria de los intereses pagados no se deduce; simétrico al INCRNGO de los arts. 38 a 41.",
    text: "No es deducible el componente inflacionario de los intereses y demás costos y gastos financieros, incluidos los ajustes por diferencia en cambio, de conformidad con el artículo 81 y siguientes. Es la contrapartida del tratamiento de INCRNGO del componente inflacionario de los rendimientos financieros percibidos por no obligados a llevar contabilidad.",
    tags: ["inflacionario","deducciones","118"],
    url: "http://www.secretariasenado.gov.co/senado/basedoc/estatuto_tributario.html#118",
    casillas: [59,60],
  },
  {
    id: "et-118-1",
    source: "ET",
    citation: "Art. 118-1 E.T.",
    title: "Subcapitalización",
    summary: "Los intereses a vinculados del exterior solo se deducen si la deuda no supera el doble del patrimonio líquido (regla 2:1), con excepciones.",
    text: "No serán deducibles los intereses generados por deudas contraídas, directa o indirectamente, a favor de vinculados económicos o partes relacionadas del exterior, cuando el monto total promedio de esas deudas exceda el resultado de multiplicar por dos (2) el patrimonio líquido del contribuyente determinado a 31 de diciembre del año gravable inmediatamente anterior. Hay excepciones para entidades vigiladas y para financiación de proyectos de infraestructura.",
    tags: ["subcapitalizacion","vinculados","118-1"],
    url: "http://www.secretariasenado.gov.co/senado/basedoc/estatuto_tributario.html#118-1",
    casillas: [60,77],
  },
  {
    id: "et-119",
    source: "ET",
    citation: "Art. 119 E.T.",
    title: "Intereses de vivienda e ICETEX",
    summary: "Intereses de adquisición de vivienda: tope 1.200 UVT. Intereses ICETEX: tope 100 UVT.",
    text: "Son deducibles los intereses que se paguen sobre préstamos para adquisición de vivienda del contribuyente, siempre que el préstamo esté garantizado con hipoteca si el acreedor no está sometido a la vigilancia del Estado. La deducción no puede exceder de mil doscientas (1.200) UVT en el año. Los intereses de créditos educativos del ICETEX son deducibles hasta cien (100) UVT anuales.",
    tags: ["vivienda","icetex"],
    url: "http://www.secretariasenado.gov.co/senado/basedoc/estatuto_tributario.html#119",
    casillas: [38,50,66,83],
  },
  {
    id: "et-126-1",
    source: "ET",
    citation: "Arts. 126-1 y 126-4 E.T.",
    title: "AFC, FVP y AVC",
    summary: "Rentas exentas hasta 30 % del ingreso y 3.800 UVT. Permanencia mínima 10 años, salvo destinación autorizada.",
    text: "Los aportes a seguros privados de pensiones, fondos de pensiones voluntarias, Cuentas AFC y AVC no hacen parte de la base de retención y son renta exenta hasta una suma que, adicionada, no exceda el 30 % del ingreso laboral o tributario del año ni 3.800 UVT. El retiro antes de 10 años, para un propósito no autorizado, hace perder el beneficio y genera las retenciones no practicadas. Los partícipes independientes pueden deducir cesantías hasta 2.500 UVT, sin exceder un doceavo del ingreso gravable.",
    tags: ["afc","fvp","exentas"],
    url: "http://www.secretariasenado.gov.co/senado/basedoc/estatuto_tributario.html#126-1",
    casillas: [35,47,63,80],
  },
  {
    id: "et-147",
    source: "ET",
    citation: "Art. 147 E.T.",
    title: "Compensación de pérdidas fiscales",
    summary: "Las pérdidas fiscales se compensan en los años siguientes, sin reajuste fiscal, con los límites vigentes.",
    text: "Las sociedades podrán compensar las pérdidas fiscales con las rentas líquidas ordinarias que obtuvieren en los periodos gravables siguientes, sin perjuicio de la renta presuntiva. Las pérdidas fiscales objeto de compensación no son susceptibles de reajuste fiscal. En personas naturales, la compensación es cedular (honorarios, capital, no laborales) según el DUR 1625/2016 art. 1.2.1.20.6.",
    tags: ["perdidas","compensacion"],
    url: "http://www.secretariasenado.gov.co/senado/basedoc/estatuto_tributario.html#147",
    casillas: [56,72,89,94],
  },
  {
    id: "et-189",
    source: "ET",
    citation: "Art. 189 E.T.",
    title: "Renta presuntiva",
    summary: "Tarifa del 0 % sobre el patrimonio líquido depurado. Aún se compara con la cédula general y se liquidan rentas de activos exceptuados.",
    text: "La renta líquida del contribuyente no puede ser inferior al porcentaje que señale la ley del patrimonio líquido del año inmediatamente anterior. Ese porcentaje es del cero por ciento (0 %). Del patrimonio líquido se restan, entre otros, aportes en sociedades nacionales, vivienda de habitación hasta 8.000 UVT y activos agropecuarios hasta 19.000 UVT. Los excesos de renta presuntiva se compensan en los términos del parágrafo del art. 189.",
    tags: ["presuntiva","patrimonio"],
    url: "http://www.secretariasenado.gov.co/senado/basedoc/estatuto_tributario.html#189",
    casillas: [98,95],
  },
  {
    id: "et-206",
    source: "ET",
    citation: "Art. 206 E.T.",
    title: "Rentas de trabajo exentas",
    summary: "Indemnizaciones, cesantías (con tabla), 25 % de pagos laborales hasta 790 UVT, pensiones hasta 1.000 UVT mensuales, y otras.",
    text: "Están gravadas con el impuesto sobre la renta las rentas de trabajo. Se exceptúan: 1) indemnizaciones por accidente de trabajo o enfermedad; 2) indemnizaciones que impliquen protección a la maternidad; 3) gastos de entierro; 4) auxilio de cesantía e intereses, con tabla cuando el salario promedio de 6 meses supera 350 UVT; 5) pensiones hasta 1.000 UVT mensuales; 6) gastos de representación de magistrados (50 %) y jueces (25 %); 7) exceso del salario básico de Fuerza Pública; 8) gastos de representación de rectores y profesores de universidades públicas hasta 50 %; 10) el 25 % de los pagos laborales, limitado a 790 UVT, calculado después de restar INCRNGO, demás exentas y deducciones. Las rentas de trabajo que no provengan de relación laboral pueden optar entre costos o la exención del numeral 10.",
    tags: ["exentas","25%","cesantias","pensiones"],
    url: "http://www.secretariasenado.gov.co/senado/basedoc/estatuto_tributario.html#206",
    casillas: [36,102],
  },
  {
    id: "et-283",
    source: "ET",
    citation: "Art. 283 E.T.",
    title: "Valor patrimonial de las deudas",
    summary: "Los no obligados a llevar libros solo pueden solicitar pasivos respaldados en documentos de fecha cierta.",
    text: "El valor de la deuda al final del año o período gravable es el patrimonial. Los contribuyentes no obligados a llevar libros de contabilidad solo podrán solicitar los pasivos que estén respaldados por documentos de fecha cierta. En los demás casos, los pasivos deben estar respaldados por documentos idóneos con las formalidades exigidas por la contabilidad. Concuerda con los arts. 767 y 770 del E.T. y con los arts. 48 a 61 del Código de Comercio.",
    tags: ["pasivos","fecha cierta","patrimonio"],
    url: "http://www.secretariasenado.gov.co/senado/basedoc/estatuto_tributario.html#283",
    casillas: [30],
  },
  {
    id: "et-303-1",
    source: "ET",
    citation: "Art. 303-1 E.T.",
    title: "Indemnizaciones por seguros de vida",
    summary: "No gravadas como ganancia ocasional hasta 3.250 UVT; el exceso tributa a la tarifa de GO.",
    text: "Las indemnizaciones por seguros de vida estarán gravadas con la tarifa aplicable a las ganancias ocasionales en el monto que supere tres mil doscientas cincuenta (3.250) UVT.",
    tags: ["ganancia ocasional","seguro"],
    url: "http://www.secretariasenado.gov.co/senado/basedoc/estatuto_tributario.html#303-1",
    casillas: [112,114],
  },
  {
    id: "et-307",
    source: "ET",
    citation: "Arts. 307 y 311-1 E.T.",
    title: "Ganancias ocasionales exentas",
    summary: "Vivienda del causante 13.000 UVT, otros inmuebles 6.500 UVT, asignaciones 3.250 UVT, donaciones 20 % hasta 1.625 UVT, utilidad en casa de habitación 5.000 UVT si va a AFC.",
    text: "Están exentas: las primeras 13.000 UVT del inmueble de vivienda de habitación del causante; 6.500 UVT de otros inmuebles del causante; 3.250 UVT de las asignaciones por porción conyugal, herencia o legado a cada heredero, legatario o cónyuge; el 20 % de lo recibido por extraños por herencias, legados, donaciones y actos gratuitos inter vivos, sin superar 1.625 UVT; libros, ropas, utensilios y mobiliario de la casa del causante. El art. 311-1 exime las primeras 5.000 UVT de la utilidad en la venta de la casa o apartamento de habitación si el producto se consigna en AFC o se abona a hipoteca de esa vivienda.",
    tags: ["ganancia ocasional","herencia","vivienda"],
    url: "http://www.secretariasenado.gov.co/senado/basedoc/estatuto_tributario.html#307",
    casillas: [114],
  },
  {
    id: "et-335",
    source: "ET",
    citation: "Art. 335 E.T.",
    title: "Cédula general",
    summary: "La cédula general agrupa rentas de trabajo, de capital y no laborales.",
    text: "La cédula general está conformada por las rentas de trabajo, las rentas de capital y las rentas no laborales. A esta cédula le es aplicable el art. 336 para obtener la renta líquida gravable.",
    tags: ["cedula","general"],
    url: "http://www.secretariasenado.gov.co/senado/basedoc/estatuto_tributario.html#335",
    casillas: [91,97],
  },
  {
    id: "et-336",
    source: "ET",
    citation: "Art. 336 E.T.",
    title: "Renta líquida gravable de la cédula general",
    summary: "40 % / 1.340 UVT, 72 UVT por dependiente (máx. 4) y 1 % de factura electrónica hasta 240 UVT.",
    text: "De los ingresos de la cédula general se restan INCRNGO, costos y gastos procedentes, rentas exentas y las deducciones imputables, observando el límite del 40 % que en todo caso no puede superar 1.340 UVT anuales (num. 3). Ese límite no aplica a las rentas exentas de los nums. 6, 7 y 8 del art. 206, a la prima especial y de costo de vida, a convenios para evitar la doble imposición ni a la Decisión 578 CAN. En adición, el trabajador puede deducir 72 UVT por dependiente hasta un máximo de cuatro (num. 4, casilla 139). El 1 % de adquisiciones con factura electrónica pagadas por medio electrónico, hasta 240 UVT, no está sujeto al 40 % y no genera pérdida (num. 5, casilla 28).",
    tags: ["40%","1340","dependientes","factura"],
    url: "http://www.secretariasenado.gov.co/senado/basedoc/estatuto_tributario.html#336",
    casillas: [28,92,93,139],
  },
  {
    id: "et-336-1",
    source: "ET",
    citation: "Art. 336-1 E.T.",
    title: "Tope indicativo de costos y gastos",
    summary: "Si los costos de honorarios superan el 60 % de los ingresos, se marca la casilla 140.",
    text: "Para las rentas de trabajo que no provengan de una relación laboral o legal y reglamentaria, los costos y gastos deducibles se estiman en 60 % de los ingresos brutos. Si el contribuyente excede ese tope indicativo debe marcarlo expresamente en la declaración (casilla 140). Los costos deben estar soportados con factura electrónica de venta, nómina electrónica o documento equivalente electrónico.",
    tags: ["honorarios","60%","casilla 140"],
    url: "http://www.secretariasenado.gov.co/senado/basedoc/estatuto_tributario.html#336-1",
    casillas: [45,140],
  },
  {
    id: "et-236",
    source: "ET",
    citation: "Arts. 236 a 239-1 E.T.",
    title: "Renta por comparación patrimonial",
    summary: "Si el patrimonio líquido aumenta más que la renta, la diferencia no justificada se adiciona como renta gravable.",
    text: "Cuando la suma de la renta gravable, las rentas exentas y la ganancia ocasional neta resultare inferior a la diferencia entre el patrimonio líquido del último día del año o período gravable y el patrimonio líquido poseído en el primer día del mismo año, se considera como renta gravable la diferencia, sin perjuicio de la determinación de la renta por el sistema ordinario. El art. 239-1 trata activos omitidos y pasivos inexistentes como renta líquida gravable.",
    tags: ["comparacion","patrimonio"],
    url: "http://www.secretariasenado.gov.co/senado/basedoc/estatuto_tributario.html#236",
    casillas: [96,31],
  },
  {
    id: "et-241",
    source: "ET",
    citation: "Art. 241 E.T.",
    title: "Tarifa para personas naturales residentes",
    summary: "Tabla marginal 0 %–39 % en UVT (Ley 2277 de 2022): 0–1.090, 19 %, 28 %, 33 %, 35 %, 37 % y 39 %.",
    text: "El impuesto sobre la renta de las personas naturales residentes se determina de conformidad con la siguiente tabla (rangos en UVT): 0 a 1.090: 0 %; >1.090 a 1.700: 19 %; >1.700 a 4.100: 28 % + 116 UVT; >4.100 a 8.670: 33 % + 786 UVT; >8.670 a 18.970: 35 % + 2.296 UVT; >18.970 a 31.000: 37 % + 5.901 UVT; >31.000: 39 % + 10.352 UVT.",
    tags: ["tarifa","impuesto"],
    url: "http://www.secretariasenado.gov.co/senado/basedoc/estatuto_tributario.html#241",
    casillas: [116,117],
  },
  {
    id: "et-242",
    source: "ET",
    citation: "Art. 242 E.T.",
    title: "Tarifa de dividendos de personas naturales residentes",
    summary: "Los dividendos del num. 3 art. 49 se suman a la cédula general (tabla 241). Los del par. 2 art. 49 se gravan a la tarifa del art. 240 (35 % general) y luego se descuenta vía 254-1.",
    text: "Los dividendos y participaciones pagados o abonados en cuenta a personas naturales residentes, provenientes de distribuciones de utilidades que hayan sido consideradas como ingreso no constitutivo de renta, estarán gravados a la tarifa establecida en el art. 241. Los provenientes de utilidades gravadas conforme al parágrafo 2 del art. 49 se gravarán a las tarifas del art. 240 (35 % general para AG 2023 y siguientes).",
    tags: ["dividendos","tarifa"],
    url: "http://www.secretariasenado.gov.co/senado/basedoc/estatuto_tributario.html#242",
    casillas: [107,108,118,124],
  },
  {
    id: "et-244-1",
    source: "ET",
    citation: "Art. 244-1 E.T.",
    title: "Aporte voluntario",
    summary: "Se puede pagar un aporte voluntario, sin beneficio tributario, destinado a programas sociales. Formulario 490, concepto 45.",
    text: "Los contribuyentes podrán realizar de manera libre un aporte voluntario, liquidado como porcentaje del impuesto a pagar o como valor en pesos. No es INCRNGO, no genera saldo a favor ni se tiene en cuenta para sanciones. Se recauda con el formulario 490, concepto 45.",
    tags: ["aporte","490"],
    url: "http://www.secretariasenado.gov.co/senado/basedoc/estatuto_tributario.html#244-1",
    casillas: [141],
  },
  {
    id: "et-254",
    source: "ET",
    citation: "Arts. 254, 254-1, 256 y 257 E.T.",
    title: "Descuentos tributarios",
    summary: "Tax credit por impuestos del exterior; 19 % sobre exceso de 1.090 UVT de dividendos; 30 % I+D+i; 25 % donaciones a ESAL. Tope conjunto 30 % del impuesto (256, 257 y 257-1).",
    text: "Las personas naturales residentes que perciban rentas de fuente extranjera gravadas en el país de origen pueden descontar el impuesto pagado en el exterior, sin que exceda el impuesto colombiano sobre esas mismas rentas (art. 254). El art. 254-1 otorga un descuento del 19 % sobre el exceso de 1.090 UVT de la renta líquida cedular de dividendos. El art. 256 (inversiones I+D+i y donaciones calificadas) y el art. 257 (donaciones a ESAL del régimen especial, 25 %) no pueden, en conjunto con el 257-1, exceder el 30 % del impuesto a cargo.",
    tags: ["descuentos","donaciones","exterior"],
    url: "http://www.secretariasenado.gov.co/senado/basedoc/estatuto_tributario.html#254",
    casillas: [122,123,124],
  },
  {
    id: "et-261",
    source: "ET",
    citation: "Arts. 261, 267, 283 E.T.",
    title: "Patrimonio bruto, valor patrimonial y deudas",
    summary: "Se declaran bienes y derechos apreciables en dinero. Los no obligados a llevar libros solo pueden solicitar pasivos de fecha cierta.",
    text: "El patrimonio bruto está constituido por el total de los bienes y derechos apreciables en dinero poseídos por el contribuyente en el último día del año o período gravable (art. 261). El valor patrimonial se determina según las reglas de los arts. 267 y siguientes (costo fiscal, avalúo, autoavalúo). Las deudas se aceptan de conformidad con el art. 283: los no obligados a llevar contabilidad solo pueden solicitar pasivos respaldados por documentos de fecha cierta.",
    tags: ["patrimonio","deudas"],
    url: "http://www.secretariasenado.gov.co/senado/basedoc/estatuto_tributario.html#261",
    casillas: [29,30,31],
  },
  {
    id: "et-300",
    source: "ET",
    citation: "Arts. 300, 303-1, 307 a 311-1 E.T.",
    title: "Ganancias ocasionales",
    summary: "Enajenación de activos fijos poseídos ≥ 2 años, herencias, donaciones, loterías. Tarifas 15 % (general) y 20 % (loterías). Exenciones en UVT para vivienda, herederos y seguro de vida.",
    text: "Son ganancias ocasionales las provenientes de la enajenación de bienes de activo fijo poseídos dos años o más, liquidación de sociedades con duración ≥ 2 años, herencias, legados, donaciones y porción conyugal, rifas y loterías. Tarifa general 15 %; loterías, rifas y apuestas 20 %. El seguro de vida no está gravado hasta 3.250 UVT (art. 303-1). Exenciones: 13.000 UVT de vivienda de habitación del causante; 6.500 UVT de otros inmuebles; 3.250 UVT para cónyuge y cada heredero; 20 % para extraños y donaciones, máx. 1.625 UVT; 5.000 UVT de utilidad en venta de casa de habitación si se destina a AFC o a hipoteca (art. 311-1).",
    tags: ["go","herencias","loterias"],
    url: "http://www.secretariasenado.gov.co/senado/basedoc/estatuto_tributario.html#300",
    casillas: [112,113,114,115,127],
  },
  {
    id: "et-330",
    source: "ET",
    citation: "Arts. 330 a 336-1 E.T.",
    title: "Sistema cedular y límite del 40 % / 1.340 UVT",
    summary: "Cédula general (trabajo, honorarios, capital, no laborales), pensiones y dividendos. El 40 % de la renta (máx. 1.340 UVT) limita exentas y deducciones. Dependientes: +72 UVT c/u (máx. 4). 1 % de factura electrónica hasta 240 UVT.",
    text: "El impuesto se determina por cédulas. La cédula general agrupa rentas de trabajo, honorarios, capital y no laborales. Las rentas exentas y deducciones imputables de la cédula general no pueden exceder el 40 % de la renta, ni 1.340 UVT (num. 3 art. 336), salvo las excepciones del DUR 1.2.1.20.4 (nums. 6, 7, 8 y 9 art. 206, primas diplomáticas, CAN, hoteles). El trabajador puede deducir adicionalmente 72 UVT por dependiente, máximo 4. El 1 % de compras con factura electrónica pagadas por medio electrónico, hasta 240 UVT, no está sujeto al 40 % (num. 5 art. 336). El art. 336-1 fija un tope indicativo de costos del 60 % para honorarios; si se supera, se marca la casilla 140.",
    tags: ["cedulas","40%","dependientes","factura"],
    url: "http://www.secretariasenado.gov.co/senado/basedoc/estatuto_tributario.html#336",
    casillas: [41,92,139,28,140],
  },
  {
    id: "et-387",
    source: "ET",
    citation: "Art. 387 E.T.",
    title: "Deducciones en la retención por salarios (salud y dependientes)",
    summary: "Medicina prepagada hasta 16 UVT mensuales. Dependientes: 10 % de la renta de trabajo, máx. 32 UVT mensuales, más 72 UVT anuales por dependiente.",
    text: "El trabajador puede disminuir de la base de retención los pagos por salud a medicina prepagada o seguros de salud vigilados, hasta 16 UVT mensuales, y la deducción por dependientes de hasta el 10 % de los ingresos laborales del mes, con tope de 32 UVT mensuales. Para AG 2023 y siguientes se adicionan 72 UVT por dependiente (máx. 4) al límite del art. 336. Un mismo dependiente no da lugar a duplicar el beneficio, salvo cuando hay rentas laborales y no laborales, caso en el cual pueden aplicarse ambas.",
    tags: ["dependientes","salud","retencion"],
    url: "http://www.secretariasenado.gov.co/senado/basedoc/estatuto_tributario.html#387",
    casillas: [39,138,139],
  },
  {
    id: "et-588",
    source: "ET",
    citation: "Arts. 588 a 589 E.T.",
    title: "Corrección de la declaración",
    summary: "El contribuyente puede corregir aumentando el impuesto o disminuyendo el saldo a favor, con sanción. Hay plazos distintos si la corrección es a favor.",
    text: "Las declaraciones tributarias podrán ser corregidas por el contribuyente, aumentando el valor a pagar o disminuyendo el saldo a favor, dentro de los tres (3) años siguientes al vencimiento del plazo para declarar, o al momento de la presentación si es extemporánea. Las correcciones que disminuyan el impuesto o aumenten el saldo a favor se rigen por el art. 589 y, en general, requieren solicitud o corrección dentro del año siguiente.",
    tags: ["correccion","sancion"],
    url: "http://www.secretariasenado.gov.co/senado/basedoc/estatuto_tributario.html#588",
    casillas: [25,26,135],
  },
  {
    id: "et-592",
    source: "ET",
    citation: "Arts. 592, 593, 594-1 y 594-3 E.T.",
    title: "Quiénes no están obligados a declarar",
    summary: "No declaran quienes, no siendo responsables de IVA, tengan ingresos y patrimonio inferiores a 1.400 y 4.500 UVT, y no superen los topes de compras, consumos y consignaciones. Los asalariados tienen reglas extra (80 % laboral).",
    text: "No están obligados a presentar declaración de renta y complementarios las personas naturales y sucesiones ilíquidas que no sean responsables del IVA, que hayan obtenido ingresos brutos inferiores a 1.400 UVT y cuyo patrimonio bruto no exceda de 4.500 UVT (art. 592). El art. 593 adiciona requisitos para asalariados (al menos 80 % de ingresos laborales, y no superar consumos, consignaciones, etc.). El art. 594-3 obliga a declarar a quienes superen 1.400 UVT en compras, consumos con tarjeta o consignaciones, depósitos e inversiones. Ser responsable de IVA al 31 de diciembre obliga a declarar.",
    tags: ["topes","obligados"],
    url: "http://www.secretariasenado.gov.co/senado/basedoc/estatuto_tributario.html#592",
  },
  {
    id: "et-639",
    source: "ET",
    citation: "Arts. 639, 641, 642 y 644 E.T.",
    title: "Sanción mínima y extemporaneidad",
    summary: "Sanción mínima: 10 UVT del año de presentación. Extemporaneidad: 5 % del impuesto por mes o fracción, con topes.",
    text: "En ningún caso las sanciones pueden ser inferiores a la equivalente a diez (10) UVT (art. 639), calculadas con la UVT del año de presentación. La sanción por extemporaneidad (art. 641) es del cinco por ciento (5 %) del valor a cargo, por cada mes o fracción, sin exceder el 100 % (o 10 % mensual después de emplazamiento, art. 642). La sanción por corrección es del 10 % de la diferencia (art. 644), 20 % si hay emplazamiento.",
    tags: ["sanciones","extemporaneidad"],
    url: "http://www.secretariasenado.gov.co/senado/basedoc/estatuto_tributario.html#639",
    casillas: [135],
  },
  {
    id: "et-689-3",
    source: "ET",
    citation: "Art. 689-3 E.T.",
    title: "Beneficio de auditoría (AG 2023 a 2026)",
    summary: "Firmeza a 6 meses si el impuesto neto sube ≥ 35 %; a 12 meses si sube ≥ 25 %. No aplica si el impuesto anterior es < 71 UVT.",
    text: "Para los años gravables 2023, 2024, 2025 y 2026, la liquidación privada quedará en firme en seis (6) meses si el impuesto neto de renta se incrementa al menos 35 % respecto del año anterior, o en doce (12) meses si el incremento es de al menos 25 %, siempre que la declaración se presente oportunamente y el pago total se realice en los plazos. No procede si el impuesto neto del año base es inferior a 71 UVT, ni para quienes gocen de beneficios por ubicación geográfica, ni si las retenciones declaradas son inexistentes.",
    tags: ["firmeza","auditoria"],
    url: "http://www.secretariasenado.gov.co/senado/basedoc/estatuto_tributario.html#689-3",
  },
  {
    id: "et-771-2",
    source: "ET",
    citation: "Art. 771-2 E.T.",
    title: "Procedencia de costos, deducciones e impuestos descontables",
    summary: "Se exige factura electrónica o documento equivalente que cumpla los requisitos legales.",
    text: "Para la procedencia de costos y deducciones en el impuesto sobre la renta, así como de los impuestos descontables en el IVA, se requerirá de facturas con el cumplimiento de los requisitos establecidos en los artículos 617 y 618 del E.T., y de las normas que regulan la factura electrónica de venta con validación previa.",
    tags: ["factura","soporte"],
    url: "http://www.secretariasenado.gov.co/senado/basedoc/estatuto_tributario.html#771-2",
    casillas: [45,60,77],
  },
  {
    id: "et-868",
    source: "ET",
    citation: "Art. 868 E.T.",
    title: "Unidad de Valor Tributario (UVT)",
    summary: "La DIAN reajusta anualmente la UVT según la inflación. Las cifras del Estatuto en UVT se convierten con el valor del año gravable; las sanciones, con el del año de presentación.",
    text: "La Unidad de Valor Tributario (UVT) es la medida de valor que permite ajustar los valores contenidos en las disposiciones relativas a los impuestos y obligaciones administrados por la DIAN. El valor se reajusta anualmente con la variación del IPC para ingresos medios certificada por el DANE. AG 2025: $49.799 (Resolución 000193 de 2024). Año 2026: $52.374 (Resolución 000238 del 15 de diciembre de 2025). Cedulario deja editar ambos valores para que la app siga vigente cuando salga la UVT de 2027 y siguientes.",
    tags: ["uvt","reajuste"],
    url: "http://www.secretariasenado.gov.co/senado/basedoc/estatuto_tributario.html#868",
  },
  {
    id: "dur-20-3",
    source: "DUR",
    citation: "Art. 1.2.1.20.3 DUR 1625/2016",
    title: "Deducción por dependientes en rentas de trabajo",
    summary: "Define quién es dependiente y cómo se aplica la deducción del 10 % / 32 UVT, más las 72 UVT adicionales.",
    text: "La deducción por dependientes aplica únicamente a ingresos de rentas de trabajo. Un mismo dependiente solo da lugar a una de las dos deducciones (10 % mensual o 72 UVT), excepto cuando hay rentas de una relación laboral y legal o reglamentaria, caso en el cual pueden aplicarse ambas. Son dependientes los hijos hasta 18 años; entre 18 y 23 si se financia educación formal; mayores de 18 con dependencia física o psicológica certificada por Medicina Legal; cónyuge o compañero permanente, padres y hermanos, por ausencia de ingresos o ingresos menores a 260 UVT, certificados por contador, o por factores físicos/psicológicos.",
    tags: ["dependientes","dur"],
    url: "https://www.funcionpublica.gov.co/eva/gestornormativo/norma.php?i=77801",
    casillas: [39,139],
  },
  {
    id: "dur-20-4",
    source: "DUR",
    citation: "Art. 1.2.1.20.4 DUR 1625/2016",
    title: "Límite de rentas exentas y deducciones de la cédula general",
    summary: "Reglamenta el 40 % / 1.340 UVT y las rentas que no se someten a ese tope.",
    text: "Para determinar el límite del 40 % (máx. 1.340 UVT) se suman los ingresos brutos de trabajo, honorarios, capital y no laborales (más rentas pasivas ECE) y se restan los INCRNGO de esas mismas cédulas. Al resultado se aplica 40 %, sin superar 1.340 UVT. A ese cupo se suman las rentas exentas a las que no se aplica el límite (incisos 3 y 4): numerales 6, 7, 8 y 9 del art. 206, primas diplomáticas, convenios para evitar doble imposición, Decisión 578 CAN y rentas hoteleras de los nums. 3 y 4 art. 207-2. El SI de Diligenciamiento reparte el cupo primero a trabajo, luego honorarios, capital y no laborales.",
    tags: ["40%","limites","dur"],
    url: "https://www.funcionpublica.gov.co/eva/gestornormativo/norma.php?i=77801",
    casillas: [41,53,69,86,92],
  },
  {
    id: "dur-20-6",
    source: "DUR",
    citation: "Art. 1.2.1.20.6 DUR 1625/2016",
    title: "Compensación de pérdidas en el sistema cedular",
    summary: "Las pérdidas de honorarios, capital y no laborales se compensan contra la misma cédula en años siguientes, sin reajuste.",
    text: "Las pérdidas fiscales de las rentas de trabajo que no provengan de una relación laboral, de las rentas de capital y de las rentas no laborales, podrán ser compensadas en los períodos gravables siguientes contra las rentas de la misma cédula, en los términos del art. 147 E.T. No son susceptibles de reajuste fiscal. Las pérdidas de 2018 y anteriores, no compensadas, pueden imputarse contra la cédula general sin afectar rentas de trabajo (parágrafo transitorio art. 330 E.T.).",
    tags: ["perdidas","dur"],
    url: "https://www.funcionpublica.gov.co/eva/gestornormativo/norma.php?i=77801",
    casillas: [56,72,89,94],
  },
  {
    id: "cco-19",
    source: "CCO",
    citation: "Art. 19 C. Co.",
    title: "Obligación de llevar contabilidad",
    summary: "Todo comerciante debe llevar contabilidad regular de sus negocios.",
    text: "Es obligación de todo comerciante: 1) matricularse en el registro mercantil; 2) inscribir en el registro todos los actos, libros y documentos respecto de los cuales la ley exija esa formalidad; 3) llevar contabilidad regular de sus negocios conforme a las prescripciones legales; 4) conservar la correspondencia y demás documentos relacionados con sus negocios o actividades, de acuerdo con la ley; 5) denunciar ante el juez la cesación en el pago corriente de sus obligaciones mercantiles.",
    tags: ["comerciante","libros"],
    url: "http://www.secretariasenado.gov.co/senado/basedoc/codigo_comercio.html#19",
  },
  {
    id: "cco-48",
    source: "CCO",
    citation: "Arts. 48 a 61 C. Co.",
    title: "Libros de comercio y fuerza probatoria",
    summary: "Los libros deben llevarse en idioma castellano, por el sistema de partida doble, y conservarse. Tienen valor probatorio si se llevan en forma legal. Conecta con el art. 283 E.T. sobre pasivos de fecha cierta.",
    text: "Todo comerciante conformará su contabilidad, libros, registros, inventarios y estados financieros en idioma castellano, por el sistema de partida doble. Los libros deben ser registrados. Los asientos deben ser cronológicos y no pueden alterarse. La conservación de libros y papeles es de diez años (art. 60). Los libros llevados en forma legal son prueba entre comerciantes (art. 61). Para el impuesto de renta, los no comerciantes no pueden solicitar pasivos que no consten en documento de fecha cierta (art. 283 E.T., concordante con arts. 767 y 770 E.T.).",
    tags: ["libros","prueba","pasivos"],
    url: "http://www.secretariasenado.gov.co/senado/basedoc/codigo_comercio.html#48",
    casillas: [30],
  },
  {
    id: "ley-2277",
    source: "LEY",
    citation: "Ley 2277 de 2022",
    title: "Reforma tributaria (puntos que rigen el 210)",
    summary: "Tabla 241, límite 1.340 UVT, 72 UVT por dependiente, 1 % factura electrónica, tarifa GO 15 %, ICA ya no es descuento, GMF y tributos 100 %.",
    text: "La Ley 2277 de 2022 modificó, entre otros, el art. 241 (tabla 0–39 %), el art. 336 (límite 40 % / 1.340 UVT, 72 UVT por dependiente, 1 % de factura electrónica hasta 240 UVT), las tarifas de ganancias ocasionales (15 % general), eliminó el ICA como descuento tributario a partir de AG 2023 y permitió la deducción del 100 % de impuestos, tasas y contribuciones con causalidad. El art. 28 creó una deducción transitoria del 150 % de salarios para hotelería en San Andrés, Providencia y Santa Catalina (AG 2023).",
    tags: ["reforma","2277"],
    url: "http://www.secretariasenado.gov.co/senado/basedoc/ley_2277_2022.html",
  },
  {
    id: "ley-2010",
    source: "LEY",
    citation: "Ley 2010 de 2019 · art. 108-5 E.T.",
    title: "Deducción por primer empleo",
    summary: "120 % de salarios de empleados menores de 28 años en su primer empleo, tope 115 UVT mensuales.",
    text: "Los contribuyentes obligados a declarar tienen derecho a deducir el 120 % de los pagos por salario de empleados menores de 28 años, siempre que se trate del primer empleo, con un máximo de 115 UVT mensuales por empleado, en el año de contratación. El Ministerio del Trabajo expide la certificación.",
    tags: ["empleo","deduccion"],
    url: "http://www.secretariasenado.gov.co/senado/basedoc/ley_2010_2019.html",
    casillas: [45,60,77],
  },
  {
    id: "ley-1715",
    source: "LEY",
    citation: "Art. 11 Ley 1715 de 2014",
    title: "Deducción por inversión en FNCE y gestión eficiente de la energía",
    summary: "50 % del valor de la inversión, en cuotas iguales durante 15 años, con certificado UPME. La matriz DIAN 2025 también cubre vehículos híbridos y eléctricos.",
    text: "Las personas naturales y jurídicas contribuyentes del impuesto sobre la renta que realicen inversiones en proyectos de fuentes no convencionales de energía (FNCE) y de gestión eficiente de la energía tendrán derecho a deducir de su renta el cincuenta por ciento (50 %) del valor de la inversión, en un período no mayor de quince (15) años. Requiere certificado de la UPME. En la determinación cedular de 2025, la DIAN admite esta deducción en trabajo, honorarios, capital y no laborales, sometida al 40 % / 1.340 UVT. Los vehículos híbridos y eléctricos se tratan, cuando la norma especial lo permite, con el mismo esquema de 50 % a 15 años.",
    tags: ["fnce","energia","vehiculos","deducciones"],
    url: "http://www.secretariasenado.gov.co/senado/basedoc/ley_1715_2014.html",
    casillas: [39,51,67,84],
  },
  {
    id: "dec-1226",
    source: "LEY",
    citation: "Decreto 1226 del 18 de agosto de 2026",
    title: "Plazos especiales de renta por el sismo del 10 de agosto",
    summary: "Corre los vencimientos de personas naturales con NIT 01–26 y domicilio fiscal en seccionales de Cali, Palmira, Tuluá, Buenaventura, Pereira, Armenia, Manizales, Quibdó y Popayán, al periodo 27 de octubre–13 de noviembre de 2026.",
    text: "El Ministerio de Hacienda, en desarrollo de los artículos 579 y 811 del E.T., fijó plazos especiales para la declaración y pago del impuesto sobre la renta de personas naturales y sucesiones ilíquidas cuyos dos últimos dígitos del NIT estén entre 01 y 26, y que al 10 de agosto de 2026 tuvieran domicilio fiscal en municipios de las direcciones seccionales de Impuestos Cali e Impuestos y Aduanas de Palmira, Tuluá, Buenaventura, Pereira, Armenia, Manizales, Quibdó y Popayán. Fechas: 01-02 el 27 de octubre; 03-04 el 28; 05-06 el 29; 07-08 el 30; 09-10 el 3 de noviembre; 11-12 el 4; 13-14 el 5; 15-16 el 6; 17-18 el 9; 19-20 el 10; 21-22 el 11; 23-24 el 12; 25-26 el 13 de noviembre de 2026. No aplica a grandes contribuyentes. El resto del país sigue el calendario general (12 de agosto a 26 de octubre). Verificado el 24 de agosto de 2026 contra Comunicados DIAN 101 y 105.",
    tags: ["calendario","sismo","plazos","1226"],
    url: "https://www.dian.gov.co/Prensa/Paginas/NG-Comunicado-de-Prensa-105-2026.aspx",
  },
  {
    id: "res-44",
    source: "RES",
    citation: "Resolución 000044 de 2024",
    title: "Prescripción del Formulario 210",
    summary: "Prescribe el Formulario 210 para el año gravable 2023 y siguientes. El instructivo se actualizó con la Resolución 000120 de 2024, compilada en la Resolución 000227 de 2025.",
    text: "La DIAN prescribió el Formulario 210 «Declaración de renta y complementario personas naturales y asimiladas residentes y sucesiones ilíquidas de causantes residentes» para el cumplimiento de las obligaciones del año gravable 2023 y siguientes. El instructivo (casillas 1 a 141, 980, 981, 982) es el que Cedulario implementa. Sigue vigente para AG 2025, a presentarse en 2026.",
    tags: ["formulario","210"],
    url: "https://www.dian.gov.co/atencionciudadano/formulariosinstructivos/Formularios/2024/Formulario_210_2024.pdf",
  },
  {
    id: "res-238",
    source: "RES",
    citation: "Resolución 000238 de 2025",
    title: "UVT 2026",
    summary: "UVT 2026 = $52.374. La UVT del año gravable 2025 (declaración de 2026) es $49.799.",
    text: "La DIAN fijó la Unidad de Valor Tributario para el año 2026 en cincuenta y dos mil trescientos setenta y cuatro pesos ($52.374). Las sanciones de la declaración presentada en 2026 se liquidan con esta UVT (p. ej. sanción mínima de 10 UVT). Los topes de obligación de declarar por AG 2025 se liquidan con la UVT 2025 ($49.799): 1.400 UVT = $69.719.000; 4.500 UVT = $224.096.000, según el micrositio oficial de la DIAN.",
    tags: ["uvt","topes"],
    url: "https://www.dian.gov.co/normatividad/Normatividad/Resoluci%C3%B3n%20000238%20de%2015-12-2025.Pdf",
  },
  {
    id: "res-227-2025",
    source: "RES",
    citation: "Resolución 000227 de 2025",
    title: "Presentación electrónica obligatoria",
    summary: "Todas las personas naturales, vivan en Colombia o en el exterior, presentan la declaración por el portal transaccional DIAN.",
    text: "De acuerdo con la Resolución 000227 del 23 de septiembre de 2025, todas las personas naturales —independientemente de si viven en Colombia o en el exterior— deberán presentar su declaración a través del portal transaccional de la DIAN, con usuario, contraseña y firma electrónica habilitados.",
    tags: ["presentacion","electronica"],
    url: "https://micrositios.dian.gov.co/renta-personas-naturales-ag-2025/todo-lo-que-usted-debe-saber-sobre-renta/",
  },
  {
    id: "can-578",
    source: "CAN",
    citation: "Decisión 578 de 2004 CAN",
    title: "Doble tributación andina",
    summary: "Las rentas por servicios personales o empresariales solo se gravan donde se prestan. En Colombia se tratan como exentas.",
    text: "El régimen para evitar la doble tributación y prevenir la evasión fiscal entre los países miembros de la Comunidad Andina prevé que las rentas provenientes de la prestación de servicios personales o empresariales solo serán gravables en el territorio en el cual tales servicios fueren prestados, salvo las excepciones de la misma Decisión. En consecuencia, las rentas obtenidas por la prestación de servicios en países CAN por residentes colombianos se consideran exentas en Colombia y no se someten al límite del 40 % / 1.340 UVT.",
    tags: ["can","exentas","doble"],
    url: "https://www.comunidadandina.org/normativa-andina/decisiones/",
    casillas: [36,64,81,110],
  },
  {
    id: "dian-topes-2025",
    source: "DIAN",
    citation: "Micrositio renta AG 2025",
    title: "Topes oficiales para declarar en 2026",
    summary: "IVA responsable; patrimonio ≥ $224.096.000; ingresos, tarjetas, compras o consignaciones ≥ $69.719.000. UVT 2025 = $49.799.",
    text: "Debe presentar declaración de renta por el año gravable 2025 quien al 31 de diciembre de 2025 haya sido responsable de IVA; o cuyo patrimonio bruto haya sido superior a 4.500 UVT ($224.096.000); o cuyos ingresos brutos, consumos con tarjeta, compras y consumos, o consignaciones/depósitos/inversiones hayan sido iguales o superiores a 1.400 UVT ($69.719.000). Formulario 210 si es residente; 110 si no lo es. Plazos generales: 12 de agosto a 26 de octubre de 2026, según los dos últimos dígitos del NIT. Plazo especial Decreto 1226 para dígitos 01–26 en seccionales afectadas por el sismo del 10 de agosto. Fuentes cruzadas el 24 de agosto de 2026 (Comunicados DIAN 090, 101 y 105).",
    tags: ["topes","calendario","oficial"],
    url: "https://micrositios.dian.gov.co/renta-personas-naturales-ag-2025/todo-lo-que-usted-debe-saber-sobre-renta/",
  },
  ...ET_EXTRA,
];

export function searchArticles(q: string): LegalArticle[] {
  const s = q.trim().toLowerCase();
  if (!s) return ARTICLES;
  return ARTICLES.filter((a) => {
    const blob = `${a.citation} ${a.title} ${a.summary} ${a.text} ${a.tags.join(" ")} ${a.id}`.toLowerCase();
    return s.split(/\s+/).every((w) => blob.includes(w));
  });
}

export function articleById(id: string) {
  return ARTICLES.find((a) => a.id === id);
}
