import type { LegalArticle } from "./articles";
import { senadoArt } from "./estatuto-index";

/** Artículos del E.T. que anclan el 210 y no estaban en el corpus operativo inicial.
 *  Resumen de trabajo: contraste siempre con el texto vigente en Secretaría del Senado.
 */
export const ET_EXTRA: LegalArticle[] = [
  {
    id: "et-5",
    source: "ET",
    citation: "Art. 5 E.T.",
    title: "El impuesto sobre la renta y sus complementarios constituyen un solo impuesto",
    summary: "Renta y ganancias ocasionales se liquidan como un solo impuesto. En el 210 van las cédulas más la sección de GO.",
    text: "El impuesto sobre la renta y sus complementarios constituyen un solo impuesto. Por eso el Formulario 210 liquida en un mismo acto las cédulas de renta (trabajo, honorarios, capital, no laborales, pensiones, dividendos) y las ganancias ocasionales, y produce un único impuesto a cargo (casilla 129) sobre el cual se imputan retenciones, anticipos y saldos.",
    tags: ["sujeto", "complementarios", "go"],
    url: senadoArt(5),
    casillas: [97, 112, 119, 129],
  },
  {
    id: "et-6",
    source: "ET",
    citation: "Art. 6 E.T.",
    title: "Declaración voluntaria del impuesto sobre la renta",
    summary: "Quien no está obligado puede declarar de forma voluntaria. Útil para solicitar saldos a favor o dejar rastro de patrimonio.",
    text: "Las personas naturales que no estén obligadas a presentar declaración de renta pueden hacerlo de manera voluntaria. Esa declaración produce los mismos efectos de una declaración obligatoria (firmeza, beneficio de auditoría, saldo a favor). En Cedulario, si no cruza topes, se indica que puede declarar voluntariamente.",
    tags: ["voluntaria", "topes"],
    url: senadoArt(6),
  },
  {
    id: "et-7",
    source: "ET",
    citation: "Art. 7 E.T.",
    title: "Las personas naturales están sometidas al impuesto",
    summary: "Las PN —residentes o no— son sujetos del impuesto de renta. El formulario depende de la residencia (art. 10).",
    text: "Las personas naturales, nacionales o extranjeras, están sometidas al impuesto sobre la renta y complementarios. Si son residentes (art. 10) usan el Formulario 210 y declaran renta mundial; si no lo son, usan el 110 y solo fuente nacional.",
    tags: ["sujeto", "persona natural"],
    url: senadoArt(7),
  },
  {
    id: "et-8",
    source: "ET",
    citation: "Art. 8 E.T.",
    title: "Los cónyuges se gravan en forma individual",
    summary: "No hay declaración conjunta. Un mismo dependiente no puede tomarse en las dos declaraciones.",
    text: "Los cónyuges, individualmente considerados, son sujetos del impuesto. Cada uno declara su patrimonio y sus rentas. El beneficio de dependientes (art. 387) no se duplica sobre la misma persona.",
    tags: ["conyuges", "dependientes"],
    url: senadoArt(8),
    casillas: [138, 139],
  },
  {
    id: "et-58",
    source: "ET",
    citation: "Art. 58 E.T.",
    title: "Realización del costo para los no obligados a llevar contabilidad",
    summary: "El costo se entiende realizado cuando se paga efectivamente, en dinero o en especie.",
    text: "Para quienes no están obligados a llevar contabilidad, los costos se realizan cuando se pagan efectivamente en dinero o en especie. Los costos anticipados se deducen en el período en que se preste el servicio o se enajene el bien. En honorarios y no laborales, esto se cruza con factura electrónica (771-2) y con el tope del 60 % (336-1).",
    tags: ["costos", "realizacion", "honorarios"],
    url: senadoArt(58),
    casillas: [45, 61, 78],
  },
  {
    id: "et-72",
    source: "ET",
    citation: "Art. 72 E.T.",
    title: "Avalúo como costo fiscal",
    summary: "El avalúo catastral o el declarado para predial puede tomarse como costo fiscal del inmueble al enajenarlo.",
    text: "Los contribuyentes pueden tomar como costo fiscal de los inmuebles el avalúo formado por las autoridades catastrales o el declarado para el impuesto predial del año anterior, menos las depreciaciones pedidas. Junto con el art. 277, el valor patrimonial mínimo es el mayor entre costo, avalúo y autoavalúo. Pida el avalúo a catastro.",
    tags: ["avaluo", "inmuebles", "costo"],
    url: senadoArt(72),
    casillas: [29, 112],
  },
  {
    id: "et-90",
    source: "ET",
    citation: "Art. 90 E.T.",
    title: "Determinación de la renta bruta en la enajenación de activos",
    summary: "Renta bruta = precio de enajenación menos costo. En bienes raíces el precio no puede ser inferior al costo, avalúo o autoavalúo.",
    text: "La renta bruta o pérdida en la enajenación de activos es la diferencia entre el precio de enajenación y el costo del activo. El precio es el valor comercial. En bienes raíces no puede ser inferior al costo fiscal, al avalúo catastral o al autoavalúo. Si el activo se poseyó dos años o más es ganancia ocasional (300); si menos, renta no laboral.",
    tags: ["enajenacion", "avaluo", "go"],
    url: senadoArt(90),
    casillas: [74, 112],
  },
  {
    id: "et-108",
    source: "ET",
    citation: "Art. 108 E.T.",
    title: "Los aportes parafiscales son requisito para la deducción de salarios",
    summary: "No hay deducción de salarios ni de prestaciones si la PILA no está al día. Los independientes necesitan cotizar para proceder costos.",
    text: "Los empleadores solo pueden deducir salarios, prestaciones y aportes si están al día en aportes a salud, pensión, riesgos, SENA, ICBF y cajas. Los trabajadores independientes que pretendan costos y deducciones deben acreditar el pago de sus aportes al sistema de seguridad social. Pida la planilla PILA.",
    tags: ["pila", "salarios", "independientes"],
    url: senadoArt(108),
    casillas: [33, 45],
  },
  {
    id: "et-125",
    source: "ET",
    citation: "Art. 125 E.T.",
    title: "Donaciones",
    summary: "Las donaciones a entidades autorizadas pueden ser deducción (125) o descuento del 25 % (257), según el régimen de la donataria.",
    text: "Las donaciones efectuadas a las entidades previstas en los artículos 22, 23 y 125 del E.T. pueden originar deducción o, si la donataria pertenece al régimen especial, el descuento del 25 % del art. 257. En ambos casos se exige certificado de la donataria con NIT y calificación. El conjunto de descuentos de los arts. 256 y 257 no puede desbordar el límite del art. 259.",
    tags: ["donaciones", "esal", "descuentos"],
    url: senadoArt(125),
    casillas: [39, 51, 67, 84, 124],
  },
  {
    id: "et-177-2",
    source: "ET",
    citation: "Art. 177-2 E.T.",
    title: "No aceptación de costos y gastos",
    summary: "No se aceptan costos o gastos que no cumplan los requisitos de causalidad, soporte o retención.",
    text: "No son aceptados los costos y gastos que no reúnan los requisitos de los artículos 107, 108, 771-2 y demás normas que el artículo 177-2 y sus concordancias exigen (operaciones sin factura, sin retención cuando hay obligación, o que no tengan relación de causalidad). En el 210 esto tumba costos de honorarios, capital y no laborales.",
    tags: ["costos", "no aceptacion", "soportes"],
    url: senadoArt("177-2"),
    casillas: [45, 61, 78],
  },
  {
    id: "et-207-2",
    source: "ET",
    citation: "Art. 207-2 E.T.",
    title: "Otras rentas exentas",
    summary: "Exenciones especiales (hotelería, energías, etc.). Varios numerales han sido derogados: contraste con el texto vigente.",
    text: "El artículo 207-2 consagra rentas exentas distintas de las de trabajo del 206 (entre ellas, en su momento, hotelería y aprovechamientos). Varios numerales fueron derogados o trasladados al 235-2. Antes de tomar una exención especial en el 210, lea el numeral vigente en Secretaría del Senado y conserve el acto administrativo que la reconoce.",
    tags: ["exentas", "especiales"],
    url: senadoArt("207-2"),
    casillas: [36, 64, 81],
  },
  {
    id: "et-239-1",
    source: "ET",
    citation: "Art. 239-1 E.T.",
    title: "Renta líquida gravable por activos omitidos o pasivos inexistentes",
    summary: "El activo omitido o el pasivo inexistente se integra como renta líquida gravable. Casilla 96.",
    text: "Los contribuyentes que declaren activos omitidos o pasivos inexistentes deben incluir su valor como renta líquida gravable por el año en que se adicionen, sin perjuicio de la sanción por inexactitud (647). En el 210 esa renta va a la casilla 96 y se suma a la renta líquida cedular para formar la casilla 97.",
    tags: ["omitidos", "comparacion", "casilla 96"],
    url: senadoArt("239-1"),
    casillas: [96, 97],
  },
  {
    id: "et-240",
    source: "ET",
    citation: "Art. 240 E.T.",
    title: "Tarifa para sociedades nacionales y extranjeras",
    summary: "Tarifa general de personas jurídicas. También se usa en la 2ª subcédula de dividendos de PN (par. 2 art. 49).",
    text: "Las sociedades nacionales y extranjeras liquidan el impuesto a la tarifa del artículo 240. En el 210 de persona natural esa tarifa se aplica a la subcédula 2 de dividendos (utilidades gravadas del parágrafo 2 del art. 49), no a la renta líquida cedular de trabajo, que va por la tabla del 241.",
    tags: ["tarifas", "dividendos", "sociedades"],
    url: senadoArt(240),
    casillas: [106, 107],
  },
  {
    id: "et-259",
    source: "ET",
    citation: "Art. 259 E.T.",
    title: "Límite de los descuentos tributarios",
    summary: "Los descuentos no pueden exceder el impuesto básico de renta. I+D y donaciones tienen tope conjunto.",
    text: "El valor de los descuentos tributarios no puede exceder el del impuesto básico de renta. Además, los descuentos de los artículos 256, 256-1 y 257 (I+D+i y donaciones) no pueden superar, en conjunto, el 25 % o el 30 % del impuesto a cargo según la redacción vigente. El exceso no se transfiere a otros años, salvo las reglas puntuales de cada descuento (p. ej. tax credit del 254).",
    tags: ["descuentos", "tope", "donaciones"],
    url: senadoArt(259),
    casillas: [123, 124, 125],
  },
  {
    id: "et-267",
    source: "ET",
    citation: "Art. 267 E.T.",
    title: "Valor patrimonial de los bienes",
    summary: "Regla general: el patrimonio se declara por su costo fiscal o por las reglas especiales de cada clase de bien.",
    text: "El valor patrimonial de los bienes poseídos a 31 de diciembre se determina según las reglas de este título: costo fiscal, avalúo, o el valor específico de cuentas, acciones, inventario, vehículos, etc. Pida al banco el certificado de saldos y a catastro el avalúo. Cruce con 261 (bruto), 277 (inmuebles) y 283 (deudas).",
    tags: ["patrimonio", "valor", "saldos"],
    url: senadoArt(267),
    casillas: [29, 31],
  },
  {
    id: "et-277",
    source: "ET",
    citation: "Art. 277 E.T.",
    title: "Valor patrimonial de los inmuebles",
    summary: "El inmueble se declara por el mayor valor entre costo fiscal, avalúo catastral y autoavalúo.",
    text: "Los inmuebles se declaran por el mayor valor entre el costo fiscal, el avalúo catastral y el autoavalúo. Ese valor alimenta la casilla 29 (patrimonio bruto) y es el piso del precio en una venta (art. 90). La vivienda de habitación no puede superar el total de inmuebles.",
    tags: ["inmuebles", "avaluo", "patrimonio"],
    url: senadoArt(277),
    casillas: [29],
  },
  {
    id: "et-365",
    source: "ET",
    citation: "Art. 365 E.T.",
    title: "Facultad para establecer retenciones",
    summary: "El Gobierno puede fijar retenciones. Lo retenido se acredita en la casilla 132 del 210.",
    text: "El Gobierno nacional tiene facultad para establecer retenciones en la fuente a título de renta. Los valores retenidos se imputan en la liquidación privada (373) y aparecen en el certificado que el agente está obligado a expedir (378 y 381). En el 210 van a la casilla 132.",
    tags: ["retencion", "agentes"],
    url: senadoArt(365),
    casillas: [132],
  },
  {
    id: "et-378",
    source: "ET",
    citation: "Art. 378 E.T.",
    title: "Certificado por concepto de salarios",
    summary: "El empleador debe expedir el certificado de ingresos y retenciones (Formato 220). Pídaselo por escrito.",
    text: "Los agentes de retención por salarios están obligados a expedir un certificado de ingresos y retenciones a cada trabajador. El contenido lo fija el art. 379 (pagos laborales, cesantías, aportes, retención). Es el primer documento que Cedulario le pide al empleador. Sin él no se cuadran las casillas 32 a 42 ni la 132.",
    tags: ["formato220", "empleador", "soportes"],
    url: senadoArt(378),
    casillas: [32, 132],
  },
  {
    id: "et-379",
    source: "ET",
    citation: "Art. 379 E.T.",
    title: "Contenido del certificado de ingresos y retenciones",
    summary: "El Formato 220 debe desglosar salarios, cesantías, aportes y retención.",
    text: "El certificado de ingresos y retenciones debe identificar al agente y al trabajador y discriminar los pagos laborales, las cesantías e intereses, los aportes obligatorios y la retención practicada. Ese desglose es el que Cedulario mapea a trabajo.salarios, cesantías, aportes y extra.retenciones.",
    tags: ["formato220", "contenido"],
    url: senadoArt(379),
    casillas: [32, 33, 132],
  },
  {
    id: "et-381",
    source: "ET",
    citation: "Art. 381 E.T.",
    title: "Certificados por otros conceptos",
    summary: "Honorarios, arrendamientos, rendimientos y dividendos también deben certificarse.",
    text: "Los agentes de retención por conceptos distintos de salarios deben expedir certificado de las sumas pagadas y de la retención practicada. Cúbrelo pidiendo el certificado al pagador de honorarios, al banco, a la sociedad que distribuyó dividendos y al arrendatario.",
    tags: ["certificados", "honorarios", "dividendos"],
    url: senadoArt(381),
    casillas: [43, 58, 104, 132],
  },
  {
    id: "et-383",
    source: "ET",
    citation: "Art. 383 E.T.",
    title: "Tarifa de retención laboral",
    summary: "Tabla mensual de retención en la fuente por salarios. No es la tarifa del 210 (esa es el art. 241).",
    text: "La retención en la fuente por pagos laborales se practica según la tabla del artículo 383, sobre una base depurada (388) que ya restó salud, pensión, dependientes y medicina prepagada (387). Esa retención se acredita en el 210; el impuesto definitivo lo liquida la tabla del 241 sobre la renta líquida gravable.",
    tags: ["retencion", "salarios", "tabla"],
    url: senadoArt(383),
    casillas: [132],
  },
  {
    id: "et-574",
    source: "ET",
    citation: "Art. 574 E.T.",
    title: "Clases de declaraciones",
    summary: "El 210 es la declaración de renta de persona natural residente. Hay otras (IVA, retención, 110).",
    text: "El Estatuto distingue las declaraciones que deben presentarse (renta, IVA, retención, patrimonio, etc.). La de renta de las personas naturales residentes y sucesiones ilíquidas de causantes residentes es el Formulario 210 prescrito por la DIAN. La de no residentes es el 110.",
    tags: ["declaracion", "210", "formularios"],
    url: senadoArt(574),
  },
  {
    id: "et-579",
    source: "ET",
    citation: "Art. 579 E.T.",
    title: "Lugares y plazos para presentar las declaraciones",
    summary: "El Gobierno fija el calendario. AG 2025: 12 de agosto a 26 de octubre de 2026, más el Decreto 1226 para la zona del sismo.",
    text: "Las declaraciones se presentan en los lugares y plazos que señale el Gobierno nacional. Para el AG 2025 el calendario general de personas naturales corre del 12 de agosto al 26 de octubre de 2026, según los dos últimos dígitos del NIT. El Decreto 1226 de 2026, con base también en el art. 811, corrió los dígitos 01–26 de ciertas seccionales del Eje Cafetero y el Pacífico. Cedulario calcula el vencimiento con su cédula.",
    tags: ["plazos", "calendario", "1226"],
    url: senadoArt(579),
  },
  {
    id: "et-596",
    source: "ET",
    citation: "Art. 596 E.T.",
    title: "Contenido de la declaración de renta",
    summary: "Identificación, patrimonio, rentas y liquidación. Firma de contador si patrimonio o ingresos superan 100.000 UVT.",
    text: "La declaración de renta debe contener la identificación del contribuyente, el patrimonio, las rentas, las ganancias ocasionales y la liquidación del impuesto, y estar firmada por el declarante. Cuando el patrimonio bruto o los ingresos brutos superen 100.000 UVT, también debe firmarla un contador público. En el 210 esas firmas van en las casillas 980 a 982.",
    tags: ["contenido", "contador", "firma"],
    url: senadoArt(596),
    casillas: [980, 981, 982],
  },
  {
    id: "et-634",
    source: "ET",
    citation: "Art. 634 E.T.",
    title: "Intereses moratorios",
    summary: "Si paga después del vencimiento de su dígito, hay intereses de mora a la tasa del art. 635.",
    text: "El no pago oportuno de las obligaciones tributarias causa intereses moratorios por cada día calendario de retardo, a la tasa prevista en el artículo 635 (usura menos dos puntos, o la que esté vigente). El vencimiento lo marca su dígito del NIT. No se liquidan intereses si no hay impuesto a cargo.",
    tags: ["mora", "intereses", "pago"],
    url: senadoArt(634),
    casillas: [136],
  },
  {
    id: "et-640",
    source: "ET",
    citation: "Art. 640 E.T.",
    title: "Principios de lesividad, proporcionalidad, gradualidad y favorabilidad",
    summary: "Las sanciones se gradúan. Un historial limpio reduce el porcentaje. Aplica la norma más favorable.",
    text: "Las sanciones del Estatuto se aplican con lesividad, proporcionalidad, gradualidad y favorabilidad. Quien no tiene sanciones en los años anteriores puede liquidar un porcentaje menor. Si una norma posterior es más benigna, se aplica. Cruce siempre con el artículo 640 y su reglamentación vigente antes de liquidar una sanción en el 210.",
    tags: ["sanciones", "gradualidad"],
    url: senadoArt(640),
  },
  {
    id: "et-641",
    source: "ET",
    citation: "Art. 641 E.T.",
    title: "Sanción por extemporaneidad",
    summary: "Por presentar después del vencimiento. Porcentaje sobre el impuesto a cargo o sobre ingresos, por mes o fracción.",
    text: "Quien presente la declaración después del vencimiento debe liquidar sanción de extemporaneidad: un porcentaje del impuesto a cargo o, si no hay impuesto, de los ingresos brutos, por cada mes o fracción de mes de retraso, con la sanción mínima de 10 UVT (639). La UVT es la del año de presentación (2026 = $52.374).",
    tags: ["extemporaneidad", "sanciones", "calendario"],
    url: senadoArt(641),
  },
  {
    id: "et-647",
    source: "ET",
    citation: "Art. 647 E.T.",
    title: "Sanción por inexactitud",
    summary: "Omite ingresos, incluye pasivos inexistentes o toma costos y deducciones improcedentes.",
    text: "Hay inexactitud cuando se omiten ingresos, se incluyen pasivos inexistentes, se toman costos, deducciones, descuentos o retenciones improcedentes, o se utiliza un dato falso que disminuya el impuesto. La sanción es un porcentaje de la diferencia. Por eso Cedulario marca soportes faltantes y diferencias entre el certificado y la casilla: no es la sanción, es la alerta para no caer en ella.",
    tags: ["inexactitud", "sanciones", "soportes"],
    url: senadoArt(647),
  },
  {
    id: "et-714",
    source: "ET",
    citation: "Art. 714 E.T.",
    title: "Firmeza de la declaración privada",
    summary: "Regla general: 3 años. Más si hay pérdidas. Menos con beneficio de auditoría (689-3).",
    text: "La declaración privada queda en firme si dentro de los tres años siguientes a su vencimiento o presentación (la que ocurra después) la DIAN no ha notificado requerimiento especial, salvo términos especiales (pérdidas, beneficio de auditoría 689-3, omisión de activos). Conserve los soportes al menos durante el término de firmeza.",
    tags: ["firmeza", "fiscalizacion", "soportes"],
    url: senadoArt(714),
  },
  {
    id: "et-771-5",
    source: "ET",
    citation: "Art. 771-5 E.T.",
    title: "Medios de pago para la procedencia de costos, deducciones y pasivos",
    summary: "Los pagos que no se hagan por los medios del artículo (depósito, transferencia, cheque, tarjeta) no son costo ni deducción, salvo umbrales.",
    text: "Para que un costo, deducción, pasivo o impuesto descontable proceda, el pago debe realizarse por los medios del artículo 771-5 (depósitos, giros, transferencias, cheques, tarjetas). Los pagos en efectivo que superen los umbrales del mismo artículo no son procedentes. Cruce el texto vigente: los topes están en UVT y han sido modificados. El 1 % de factura electrónica (num. 5 art. 336) exige, además, medio electrónico de entidad vigilada.",
    tags: ["medios de pago", "efectivo", "costos"],
    url: senadoArt("771-5"),
    casillas: [28, 45, 61, 78],
  },
];
