/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AsistenteRouteImport } from './routes/asistente'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as CedulasRouteImport } from './routes/cedulas'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as DeclaracionRouteImport } from './routes/declaracion'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as FormularioRouteImport } from './routes/formulario'
import { Route as LiquidacionRouteImport } from './routes/liquidacion'
import { Route as TopesRouteImport } from './routes/topes'
import { Route as BibliotecaIdRouteImport } from './routes/biblioteca.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AsistenteRoute = AsistenteRouteImport.update({
  id: '/asistente',
  path: '/asistente',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const CedulasRoute = CedulasRouteImport.update({
  id: '/cedulas',
  path: '/cedulas',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const DeclaracionRoute = DeclaracionRouteImport.update({
  id: '/declaracion',
  path: '/declaracion',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const FormularioRoute = FormularioRouteImport.update({
  id: '/formulario',
  path: '/formulario',
  getParentRoute: () => rootRouteImport,
} as any)
const LiquidacionRoute = LiquidacionRouteImport.update({
  id: '/liquidacion',
  path: '/liquidacion',
  getParentRoute: () => rootRouteImport,
} as any)
const TopesRoute = TopesRouteImport.update({
  id: '/topes',
  path: '/topes',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaIdRoute = BibliotecaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BibliotecaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/asistente': typeof AsistenteRoute
  '/biblioteca': typeof BibliotecaRouteWithChildren
  '/calendario': typeof CalendarioRoute
  '/cedulas': typeof CedulasRoute
  '/clientes': typeof ClientesRoute
  '/declaracion': typeof DeclaracionRoute
  '/documentos': typeof DocumentosRoute
  '/formulario': typeof FormularioRoute
  '/liquidacion': typeof LiquidacionRoute
  '/topes': typeof TopesRoute
  '/biblioteca/$id': typeof BibliotecaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/asistente': typeof AsistenteRoute
  '/biblioteca': typeof BibliotecaRouteWithChildren
  '/calendario': typeof CalendarioRoute
  '/cedulas': typeof CedulasRoute
  '/clientes': typeof ClientesRoute
  '/declaracion': typeof DeclaracionRoute
  '/documentos': typeof DocumentosRoute
  '/formulario': typeof FormularioRoute
  '/liquidacion': typeof LiquidacionRoute
  '/topes': typeof TopesRoute
  '/biblioteca/$id': typeof BibliotecaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/asistente': typeof AsistenteRoute
  '/biblioteca': typeof BibliotecaRouteWithChildren
  '/calendario': typeof CalendarioRoute
  '/cedulas': typeof CedulasRoute
  '/clientes': typeof ClientesRoute
  '/declaracion': typeof DeclaracionRoute
  '/documentos': typeof DocumentosRoute
  '/formulario': typeof FormularioRoute
  '/liquidacion': typeof LiquidacionRoute
  '/topes': typeof TopesRoute
  '/biblioteca/$id': typeof BibliotecaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/asistente'
    | '/biblioteca'
    | '/calendario'
    | '/cedulas'
    | '/clientes'
    | '/declaracion'
    | '/documentos'
    | '/formulario'
    | '/liquidacion'
    | '/topes'
    | '/biblioteca/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/asistente'
    | '/biblioteca'
    | '/calendario'
    | '/cedulas'
    | '/clientes'
    | '/declaracion'
    | '/documentos'
    | '/formulario'
    | '/liquidacion'
    | '/topes'
    | '/biblioteca/$id'
  id:
    | '__root__'
    | '/'
    | '/asistente'
    | '/biblioteca'
    | '/calendario'
    | '/cedulas'
    | '/clientes'
    | '/declaracion'
    | '/documentos'
    | '/formulario'
    | '/liquidacion'
    | '/topes'
    | '/biblioteca/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AsistenteRoute: typeof AsistenteRoute
  BibliotecaRoute: typeof BibliotecaRouteWithChildren
  CalendarioRoute: typeof CalendarioRoute
  CedulasRoute: typeof CedulasRoute
  ClientesRoute: typeof ClientesRoute
  DeclaracionRoute: typeof DeclaracionRoute
  DocumentosRoute: typeof DocumentosRoute
  FormularioRoute: typeof FormularioRoute
  LiquidacionRoute: typeof LiquidacionRoute
  TopesRoute: typeof TopesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asistente': {
      id: '/asistente'
      path: '/asistente'
      fullPath: '/asistente'
      preLoaderRoute: typeof AsistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cedulas': {
      id: '/cedulas'
      path: '/cedulas'
      fullPath: '/cedulas'
      preLoaderRoute: typeof CedulasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/declaracion': {
      id: '/declaracion'
      path: '/declaracion'
      fullPath: '/declaracion'
      preLoaderRoute: typeof DeclaracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formulario': {
      id: '/formulario'
      path: '/formulario'
      fullPath: '/formulario'
      preLoaderRoute: typeof FormularioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liquidacion': {
      id: '/liquidacion'
      path: '/liquidacion'
      fullPath: '/liquidacion'
      preLoaderRoute: typeof LiquidacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topes': {
      id: '/topes'
      path: '/topes'
      fullPath: '/topes'
      preLoaderRoute: typeof TopesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca/$id': {
      id: '/biblioteca/$id'
      path: '/$id'
      fullPath: '/biblioteca/$id'
      preLoaderRoute: typeof BibliotecaIdRouteImport
      parentRoute: typeof BibliotecaRoute
    }
  }
}

interface BibliotecaRouteChildren {
  BibliotecaIdRoute: typeof BibliotecaIdRoute
}

const BibliotecaRouteChildren: BibliotecaRouteChildren = {
  BibliotecaIdRoute: BibliotecaIdRoute,
}

const BibliotecaRouteWithChildren = BibliotecaRoute._addFileChildren(
  BibliotecaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AsistenteRoute: AsistenteRoute,
  BibliotecaRoute: BibliotecaRouteWithChildren,
  CalendarioRoute: CalendarioRoute,
  CedulasRoute: CedulasRoute,
  ClientesRoute: ClientesRoute,
  DeclaracionRoute: DeclaracionRoute,
  DocumentosRoute: DocumentosRoute,
  FormularioRoute: FormularioRoute,
  LiquidacionRoute: LiquidacionRoute,
  TopesRoute: TopesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
